// The one trust + status vocabulary. Ported from semester app/src/lib/source.ts and lib/status.ts.
// Every state = glyph + word + tone. Tone is the least of the three.
export const SOURCES = {
  official:  { label: 'Institution verified', short: 'Official', glyph: '◆', tone: 'official', fill: 'solid', meaning: 'Confirmed by your institution’s own system.' },
  connected: { label: 'Connected', short: 'Connected', glyph: '⇄', tone: 'connected', fill: 'outline', meaning: 'Synced from a connected account or feed. Semester has not checked it with your institution.' },
  imported:  { label: 'Imported', short: 'Imported', glyph: '↓', tone: 'connected', fill: 'outline', meaning: 'Copied in from a file or feed. Semester has not checked it with your institution.' },
  personal:  { label: 'Student entered', short: 'Yours', glyph: '○', tone: 'personal', fill: 'outline', meaning: 'You typed this in. Semester has not checked it with your institution.' },
  made:      { label: 'Made here', short: 'Made here', glyph: '○', tone: 'personal', fill: 'outline', meaning: 'Semester built this from sources you gave it — a rule-based extraction, not an AI draft.' },
  ai:        { label: 'AI-assisted', short: 'AI-assisted', glyph: '✦', tone: 'ai', fill: 'outline', meaning: 'Written with Semester’s assistant. It is not an official answer — check anything you act on.' },
  estimated: { label: 'Estimated', short: 'Estimated', glyph: '≈', tone: 'pending', fill: 'outline', meaning: 'Worked out by Semester from what it knows. Not an official figure.' },
  review:    { label: 'Needs review', short: 'Review', glyph: '?', tone: 'pending', fill: 'outline', meaning: 'Something about this looks wrong or out of date. Check it before relying on it.' },
  stale:     { label: 'Unavailable or stale', short: 'Stale', glyph: '!', tone: 'danger', fill: 'outline', meaning: 'Semester cannot confirm that this information is current.' },
  external:  { label: 'External', short: 'External', glyph: '↗', tone: 'neutral', fill: 'outline', meaning: 'From a source outside your institution and outside Semester, such as a web page.' },
  sample:    { label: 'Sample', short: 'Sample', glyph: '◌', tone: 'neutral', fill: 'dashed', meaning: 'Illustrative data. Not live.' },
};
export const STATUSES = {
  saving: { label: 'Saving…', glyph: '…', tone: 'neutral' },
  saved: { label: 'Saved', glyph: '✓', tone: 'success' },
  syncing: { label: 'Syncing', glyph: '↻', tone: 'neutral' },
  synced: { label: 'Synced', glyph: '✓', tone: 'success' },
  offline: { label: 'Offline', glyph: '⊘', tone: 'pending', urgent: true },
  queued: { label: 'Queued', glyph: '⋯', tone: 'neutral' },
  conflict: { label: 'Conflict needs review', glyph: '⇄', tone: 'danger', urgent: true },
  'sync-error': { label: 'Sync trouble', glyph: '!', tone: 'danger', urgent: true },
  'needs-confirmation': { label: 'Needs confirmation', glyph: '?', tone: 'pending' },
  'action-required': { label: 'Action required', glyph: '!', tone: 'pending' },
  pending: { label: 'Pending approval', glyph: '◷', tone: 'pending' },
  approved: { label: 'Approved', glyph: '✓', tone: 'success' },
  rejected: { label: 'Rejected', glyph: '✕', tone: 'danger' },
  verified: { label: 'Verified', glyph: '✓', tone: 'success' },
  hold: { label: 'Hold on account', glyph: '!', tone: 'danger' },
  'faculty-approved': { label: 'Faculty-approved', glyph: '◆', tone: 'success' },
  'course-provided': { label: 'Course-provided', glyph: '◇', tone: 'official' },
  'updated-today': { label: 'Updated today', glyph: '↻', tone: 'neutral' },
  draft: { label: 'Draft', glyph: '○', tone: 'neutral' },
  live: { label: 'Live', glyph: '●', tone: 'success' },
  beta: { label: 'Preview', glyph: '◌', tone: 'neutral' },
  'device-only': { label: 'On this device only', glyph: '○', tone: 'neutral' },
  'signed-out': { label: 'Not signed in', glyph: '○', tone: 'neutral' },
  unknown: { label: 'Status unknown', glyph: '·', tone: 'neutral' },
};
