#!/usr/bin/env python3
"""
Write a course guide as a document: Word and PDF, from the same data the app
reads.

    python3 pipeline/handout.py econ
    python3 pipeline/handout.py --all

Why both: the .docx opens in Word, in Pages, and in Google Docs (upload it to
Drive and it converts), so the guide can be annotated and shared the way
coursework actually gets shared. The PDF is for reading and printing, and is
what a phone can hold offline without an app at all.

Output: app/public/handouts/<course>.docx and .pdf, which the guide's Doc mode
links to.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

sys.path.insert(0, str(Path(__file__).resolve().parent))
from guide_reader import ROOT, all_courses, read_guide, unit_title  # noqa: E402

OUT = ROOT / "app/public/handouts"

# Print is paper: dark ink on white, not the app's dark ground. A handout gets
# printed, and a black page is a cartridge.
INK = RGBColor(0x11, 0x13, 0x18)
GREY = RGBColor(0x5A, 0x60, 0x6B)


def docx(course: str) -> Path:
    guide = read_guide(course)
    doc = Document()

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)

    title = doc.add_paragraph()
    run = title.add_run(guide["code"])
    run.font.size = Pt(26)
    run.font.bold = True
    run.font.color.rgb = INK

    sub = doc.add_paragraph()
    run = sub.add_run(f"{guide['name']} — {guide['blurb']}")
    run.font.size = Pt(11)
    run.font.color.rgb = GREY

    meta = doc.add_paragraph()
    run = meta.add_run(
        f"{len(guide['units'])} units · "
        f"{sum(len(u['cards']) for u in guide['units'])} cards · built from {guide['source']}"
    )
    run.font.size = Pt(9)
    run.font.color.rgb = GREY

    for i, unit in enumerate(guide["units"], 1):
        heading = doc.add_paragraph()
        run = heading.add_run(f"{i}. {unit_title(unit['name'])}")
        run.font.size = Pt(15)
        run.font.bold = True
        run.font.color.rgb = INK
        heading.paragraph_format.space_before = Pt(16)

        for card in unit["cards"]:
            q = doc.add_paragraph()
            run = q.add_run(card["q"])
            run.font.bold = True
            q.paragraph_format.space_after = Pt(2)
            a = doc.add_paragraph(card["a"])
            a.paragraph_format.space_after = Pt(8)

    if guide["terms"]:
        doc.add_page_break()
        heading = doc.add_paragraph()
        run = heading.add_run("Terms")
        run.font.size = Pt(15)
        run.font.bold = True
        for term in guide["terms"]:
            p = doc.add_paragraph()
            run = p.add_run(f"{term['t']} — ")
            run.font.bold = True
            p.add_run(term["d"])
            p.paragraph_format.space_after = Pt(6)

    if guide["selfTest"]:
        heading = doc.add_paragraph()
        run = heading.add_run("Self-test")
        run.font.size = Pt(15)
        run.font.bold = True
        heading.paragraph_format.space_before = Pt(16)
        # Questions first, answers at the back — a self-test with the answer
        # underneath is a reading list.
        for n, card in enumerate(guide["selfTest"], 1):
            p = doc.add_paragraph(f"{n}. {card['q']}")
            p.paragraph_format.space_after = Pt(4)
        doc.add_page_break()
        heading = doc.add_paragraph()
        run = heading.add_run("Self-test answers")
        run.font.size = Pt(15)
        run.font.bold = True
        for n, card in enumerate(guide["selfTest"], 1):
            p = doc.add_paragraph()
            run = p.add_run(f"{n}. ")
            run.font.bold = True
            p.add_run(card["a"])
            p.paragraph_format.space_after = Pt(6)

    footer = doc.add_paragraph()
    run = footer.add_run(
        "Generated by pipeline/handout.py from the app's own course data. "
        "Anything added in the app after this was written is not in here — re-run it."
    )
    run.font.size = Pt(8)
    run.font.color.rgb = GREY
    footer.alignment = WD_ALIGN_PARAGRAPH.LEFT

    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{course}.docx"
    doc.save(str(path))
    return path


def pdf(course: str) -> Path:
    guide = read_guide(course)
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{course}.pdf"

    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle("t", parent=base["Title"], fontSize=26, alignment=0, spaceAfter=4),
        "sub": ParagraphStyle("s", parent=base["Normal"], fontSize=11, textColor="#5a606b"),
        "unit": ParagraphStyle("u", parent=base["Heading2"], fontSize=15, spaceBefore=16, spaceAfter=6),
        "q": ParagraphStyle("q", parent=base["Normal"], fontSize=10.5, leading=14, spaceAfter=1, fontName="Helvetica-Bold"),
        "a": ParagraphStyle("a", parent=base["Normal"], fontSize=10.5, leading=14, spaceAfter=8),
        "small": ParagraphStyle("m", parent=base["Normal"], fontSize=8, textColor="#5a606b"),
    }

    def esc(s: str) -> str:
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    flow = [
        Paragraph(esc(guide["code"]), styles["title"]),
        Paragraph(esc(f"{guide['name']} — {guide['blurb']}"), styles["sub"]),
        Paragraph(
            esc(
                f"{len(guide['units'])} units · "
                f"{sum(len(u['cards']) for u in guide['units'])} cards · built from {guide['source']}"
            ),
            styles["small"],
        ),
        Spacer(1, 10),
        HRFlowable(width="100%", color="#c4c8ce"),
    ]

    for i, unit in enumerate(guide["units"], 1):
        flow.append(Paragraph(esc(f"{i}. {unit_title(unit['name'])}"), styles["unit"]))
        for card in unit["cards"]:
            flow.append(Paragraph(esc(card["q"]), styles["q"]))
            flow.append(Paragraph(esc(card["a"]), styles["a"]))

    if guide["terms"]:
        flow.append(PageBreak())
        flow.append(Paragraph("Terms", styles["unit"]))
        for term in guide["terms"]:
            flow.append(Paragraph(esc(term["t"]), styles["q"]))
            flow.append(Paragraph(esc(term["d"]), styles["a"]))

    if guide["selfTest"]:
        flow.append(PageBreak())
        flow.append(Paragraph("Self-test", styles["unit"]))
        for n, card in enumerate(guide["selfTest"], 1):
            flow.append(Paragraph(esc(f"{n}. {card['q']}"), styles["a"]))
        flow.append(PageBreak())
        flow.append(Paragraph("Self-test answers", styles["unit"]))
        for n, card in enumerate(guide["selfTest"], 1):
            flow.append(Paragraph(esc(f"{n}. {card['a']}"), styles["a"]))

    SimpleDocTemplate(
        str(path),
        pagesize=LETTER,
        leftMargin=0.9 * inch,
        rightMargin=0.9 * inch,
        topMargin=0.8 * inch,
        bottomMargin=0.8 * inch,
        title=f"{guide['code']} study guide",
    ).build(flow)
    return path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("course", nargs="?")
    ap.add_argument("--all", action="store_true")
    args = ap.parse_args()

    for course in all_courses() if args.all or not args.course else [args.course]:
        w = docx(course)
        p = pdf(course)
        print(f"{w}  {w.stat().st_size // 1024} KB")
        print(f"{p}  {p.stat().st_size // 1024} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
