import { EmptyState, FilePick, Notice } from './ui';
import {useEffect,useState} from 'react';
import {useDeviceLibrary} from '../lib/device-library';
import {readStoredDirectory,readIds,EMPTY_IDS,EMPTY_HOUSING,EMPTY_MEALS,readHousingDraft,readMealDraft} from '../lib/portal-storage';
import {parseDirectory,directoryTemplate,type CampusDirectoryData,type CampusListing,type DirectoryKind} from '../lib/campusdirectory';
import {download} from '../lib/deliver';
export function CampusDirectory({kind,onPlan}:{kind:DirectoryKind;onPlan?:(item:CampusListing)=>void}){
 const key=`semester.directory.${kind}`;
 const directory=useDeviceLibrary(key,readStoredDirectory,null);const selections=useDeviceLibrary(`${key}.saved`,readIds,EMPTY_IDS);const data=directory.value;const setData=directory.update;const saved=selections.value;const setSaved=selections.update;
 const [undo,setUndo]=useState<CampusDirectoryData|null>(null);const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [view,setView]=useState('all');const [message,setMessage]=useState('');
 const label=kind==='housing'?'housing options':kind==='dining'?'dining & meal plans':'clubs & organizations';const all=data?.items||[];const favorites=all.filter(i=>saved.includes(i.id));const shown=all.filter(i=>(view==='all'||saved.includes(i.id))&&(!category||i.category===category)&&`${i.name} ${i.category} ${i.description} ${i.location}`.toLowerCase().includes(query.toLowerCase()));
 const upload=async(f:File)=>{try{if(f.size>2_000_000)throw new Error('Choose a file smaller than 2 MB.');const next=parseDirectory(await f.text());if(!setData(next))return;setCategory('');setMessage(`Imported ${next.items.length} entries from ${next.institution}.`);}catch(e){setMessage(e instanceof Error?e.message:'Unable to import this directory.');}};
 return <section className={`campus-directory directory-${kind}`}><header className="portal-banner"><div><span className="portal-eyebrow">Campus directory</span><h2>Explore {label}</h2><p>{kind==='housing'?'Find a place that fits your needs. Save options and compare them before applying.':kind==='dining'?'Find places to eat, check the details and compare your meal options.':'Find your community. Discover organizations and bring their activities into your week.'}</p></div><FilePick block={false} multiple={false} accept=".json,application/json" onPick={files=>{if(files[0])void upload(files[0]);}}>Import school directory</FilePick></header><div className="portal-filter-row"><label className="portal-search"><input type="search" aria-label={`Search ${label}`} placeholder={`Search ${label}`} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Directory category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{[...new Set(all.map(i=>i.category))].map(c=><option key={c}>{c}</option>)}</select><button aria-pressed={view==='saved'} onClick={()=>setView(view==='all'?'saved':'all')}>☆ Saved ({favorites.length})</button></div>
 {(directory.error||selections.error)&&<Notice alert>{directory.error||selections.error}<button onClick={()=>download({name:`Semester ${kind} recovery.json`,body:JSON.stringify({directory:directory.recovery(),selections:selections.recovery()}),mime:'application/json'})}>Download recovery copy</button></Notice>}{data&&<p className="portal-muted">{data.institution} · Imported {new Date(data.updated).toLocaleDateString()} · Details reflect the supplied directory.</p>}{message&&<p role="status" className="portal-notice">{message}{undo&&<button onClick={()=>{if(!setData(undo))return;setUndo(null);setMessage('Directory restored.');}}>Undo removal</button>}</p>}
 {!all.length?<div className="portal-empty"><div className="portal-empty-icon">{kind==='housing'?'⌂':kind==='dining'?'☷':'♧'}</div><h3>A directory from your school belongs here</h3><p>{kind==='clubs'?'Import organization profiles, meeting information, events and membership links. Your personal activities remain available in My week.':kind==='housing'?'Import residence profiles, room types, costs and application links. Your saved residence and move-out planning remain available in My housing.':'Import dining locations, menus, hours, dietary options and meal plan details. Your balances and spending plan remain available in My meal plan.'}</p><FilePick block={false} multiple={false} accept=".json" onPick={files=>{if(files[0])void upload(files[0]);}}>Import directory</FilePick><button onClick={()=>download({name:`Semester ${kind} directory template.json`,body:JSON.stringify(directoryTemplate(kind),null,2),mime:'application/json'})}>Download school template</button></div>:<div className="portal-card-grid">{shown.map(item=><article key={item.id} className="portal-panel directory-card"><div className="directory-card-top"><span className="portal-tag">{item.category}</span><button className="directory-star" aria-label={`${saved.includes(item.id)?'Unsave':'Save'} ${item.name}`} aria-pressed={saved.includes(item.id)} onClick={()=>setSaved(ids=>ids.includes(item.id)?ids.filter(id=>id!==item.id):[...ids,item.id])}>{saved.includes(item.id)?'★':'☆'}</button></div><h3>{item.name}</h3><p className="portal-muted">{item.location||'Location not supplied'}</p><p>{item.description||'Select the official listing for more information.'}</p><details><summary>{kind==='clubs'?'Meetings, events & membership':'View details'}</summary><dl>{Object.entries(item.details).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}{item.contact&&<><dt>Contact</dt><dd>{item.contact}</dd></>}</dl></details><div className="portal-actions">{onPlan&&<button className="portal-primary" onClick={()=>onPlan(item)}>{kind==='clubs'?'Add to my week':kind==='housing'?'Plan application':'Use in my plan'}</button>}{item.url&&<a className="portal-button" href={item.url} target="_blank" rel="noreferrer">Official listing ↗</a>}</div></article>)}</div>}{!!all.length&&!shown.length&&<EmptyState inline title="No entries match" body="Try another category or search."/>}
 {view==='saved'&&favorites.length>0&&<section className="portal-panel directory-comparison"><h3>Compare saved choices</h3><div className="portal-table-scroll"><table><thead><tr><th>Detail</th>{favorites.map(i=><th key={i.id}>{i.name}</th>)}</tr></thead><tbody><tr><th>Location</th>{favorites.map(i=><td key={i.id}>{i.location||'Not supplied'}</td>)}</tr>{[...new Set(favorites.flatMap(i=>Object.keys(i.details)))].map(k=><tr key={k}><th>{k}</th>{favorites.map(i=><td key={i.id}>{i.details[k]||'Not supplied'}</td>)}</tr>)}</tbody></table></div><button onClick={()=>download({name:`Semester saved ${kind}.json`,body:JSON.stringify({institution:data?.institution,status:'saved-preferences-only',items:favorites},null,2),mime:'application/json'})}>Export saved choices</button></section>}
 {!!all.length&&<details className="portal-import-help"><summary>Update this directory</summary><button onClick={()=>{if(!setData(null))return;setUndo(data);setMessage('Imported directory removed. Saved choices remain available if matching entries are imported again.');}}>Remove imported directory</button><p>Import a new school file to replace the directory. Saved choices are kept for entries with the same IDs. Availability, fees and hours are supplied by the institution; this workspace does not confirm bookings or memberships.</p><button onClick={()=>download({name:`Semester ${kind} directory template.json`,body:JSON.stringify(directoryTemplate(kind),null,2),mime:'application/json'})}>Download school template</button></details>}
 </section>;
}
export function HousingPlanner({choice,term}:{choice:string;term:string}){
 const library=useDeviceLibrary(`semester.housing-plan.${term}`,readHousingDraft,EMPTY_HOUSING);const plan=library.value;const setPlan=library.update;const status=library.error||'Changes save on this device';
 useEffect(()=>{if(choice)setPlan(p=>({...p,residence:choice}));},[choice,setPlan]);
 return <section className="portal-panel"><h3>Housing application plan</h3><span className="portal-tag">{term}</span><p>Keep preferences and a checklist ready for the housing office. This is a private draft, not a submitted application.</p><div className="portal-form-grid">{[['residence','Preferred residence'],['roomType','Room type'],['roommate','Roommate preference']].map(([id,label])=><label key={id}>{label}<input className="input" value={String(plan[id as keyof typeof plan])} onChange={e=>setPlan(p=>({...p,[id]:e.target.value}))}/></label>)}<label>Questions for the housing office<textarea className="input" value={plan.notes} onChange={e=>setPlan(p=>({...p,notes:e.target.value}))}/></label></div><h4>Application checklist</h4>{['Review eligibility and deadlines','Compare room types and costs','Discuss roommate preferences','Submit through the official housing portal','Record the confirmed assignment','Review move-in and move-out instructions'].map(task=><label className="portal-check checklist-row" key={task}><input type="checkbox" checked={plan.checks.includes(task)} onChange={()=>setPlan(p=>({...p,checks:p.checks.includes(task)?p.checks.filter((t:string)=>t!==task):[...p.checks,task]}))}/>{task}</label>)}<div className="portal-actions"><button onClick={()=>download({name:'Semester housing application plan.json',body:JSON.stringify({status:'draft-not-submitted',term,...plan},null,2),mime:'application/json'})}>Export application plan</button><span role="status" className="portal-muted">{status}</span></div></section>;
}
export function MealPlanner({choice,term}:{choice:string;term:string}){
 const library=useDeviceLibrary(`semester.meal-plan.${term}`,readMealDraft,EMPTY_MEALS);const plan=library.value;const setPlan=library.update;const status=library.error||'Changes save on this device';
 useEffect(()=>{if(choice)setPlan(p=>({...p,name:choice}));},[choice,setPlan]);const meals=Number(plan.weekly)*Number(plan.weeks);const valid=[Number(plan.weekly),Number(plan.weeks),Number(plan.cost),meals].every(n=>Number.isFinite(n)&&n>0);
 return <section className="portal-panel"><h3>Plan your meals</h3><span className="portal-tag">{term}</span><p>Estimate value using the meals you expect to eat. Prices and eligibility should come from your school.</p><div className="portal-form-grid"><label>Plan name<input className="input" value={plan.name} onChange={e=>setPlan(p=>({...p,name:e.target.value}))}/></label>{[['weekly','Meals per week'],['weeks','Weeks on campus'],['cost','Plan cost ($)']].map(([id,label])=><label key={id}>{label}<input type="number" min="0" step={id==='cost'?'.01':'1'} className="input" value={plan[id as keyof typeof plan]} onChange={e=>setPlan(p=>({...p,[id]:e.target.value}))}/></label>)}</div>{valid?<div className="portal-stats"><div><strong>{meals}</strong><span>Expected meals</span></div><div><strong>${(Number(plan.cost)/meals).toFixed(2)}</strong><span>Estimated cost per meal</span></div><div><strong>${(Number(plan.cost)/Number(plan.weeks)).toFixed(2)}</strong><span>Cost per week</span></div></div>:<p className="portal-muted">Enter meals, weeks and cost to see an estimate.</p>}<p className="portal-muted">This estimate excludes unused benefits, rollover, guest meals and additional purchases. It does not change your enrolled meal plan.</p><span role="status" className="portal-muted">{status}</span></section>;
}
