import { StudyStudio } from './StudyStudio';
import { TabList } from './ui';
import {useState,type ReactNode} from 'react';
import {useStore} from '../state/store';
import {useLive} from '../lib/live';
import {modesFor} from '../lib/modes';
import {datedItems} from '../lib/select';
import {split,standingOf} from '../lib/standing';
import {nameFor} from '../lib/yours';
import {DeadlineRow} from './DeadlineRow';
import {type Course} from '../lib/types';
import {ForThis} from './ForThis';
export function CourseHub({course,information}:{course:Course;information:ReactNode}){
 const {state,dispatch,now,catalog}=useStore();const live=useLive(course.id);const modes=modesFor(catalog,course.id,live);
 const [studio,setStudio]=useState(false);const [tab,setTab]=useState('overview');const [filter,setFilter]=useState('upcoming');const [query,setQuery]=useState('');
 const all=datedItems(catalog,now).filter(i=>i.c===course.id);const groups=split(all,state.done);const next=groups.ahead[0];
 const matches=(text:string)=>text.toLowerCase().includes(query.trim().toLowerCase());
 const assignments=all.filter(i=>matches(`${i.title} ${i.kind} ${i.detail}`)).filter(i=>filter==='all'||filter==='completed'&&state.done[i.id]||filter==='past'&&i.date<now||filter==='upcoming'&&!state.done[i.id]&&i.date>=now);
 const readingItems=all.filter(i=>/read/i.test(i.kind));
 const ready=modes.filter(m=>m.ready);const updates=state.updates.filter(u=>u.courseId===course.id);
 if(studio)return <StudyStudio courseId={course.id} onClose={()=>setStudio(false)}/>;
 return <div className="course-hub portal-workspace"><header className="course-banner"><span className="portal-eyebrow">{course.code} · {state.sample?'Sample course':state.term}</span><h2>{nameFor(course,state.yours)}</h2><p>{course.prof||'Instructor not provided'} · {course.meets||'Schedule not provided'}{course.room?` · ${course.room}`:''}</p><div className="portal-actions"><button className="portal-primary" onClick={()=>dispatch({type:'openGuide',id:course.id})}>Continue studying →</button><button onClick={()=>dispatch({type:'openUpdate',courseId:course.id,unit:null})}>+ Add reading</button>{course.email&&<button onClick={()=>dispatch({type:'writeMail',courseId:course.id,purposeId:'question'})}>Email instructor</button>}</div></header><TabList label="Course workspace" className="portal-tabs" value={tab} onChange={id=>{setTab(id);setQuery('');}} tabs={([['overview','Overview'],['assignments','Assignments'],['study','Study tools'],['readings','Readings & materials'],['information','Syllabus & class info']] as [typeof tab,string][]).map(([id,label])=>({id,label}))}/>
 {tab==='overview'&&<><div className="portal-stats"><button onClick={()=>{setTab('assignments');setFilter('upcoming');}}><strong>{groups.ahead.length}</strong><span>Upcoming</span></button><button onClick={()=>{setTab('assignments');setFilter('past');}}><strong>{groups.overdue.length}</strong><span>Past due · unresolved</span></button><button onClick={()=>{setTab('assignments');setFilter('completed');}}><strong>{groups.done.length}</strong><span>Completed</span></button><button onClick={()=>setTab('study')}><strong>{ready.length}</strong><span>Study modes ready</span></button></div><div className="portal-columns"><section className="portal-panel"><h3>What’s next</h3>{next?<><DeadlineRow item={next} tone="ahead"/><ForThis item={next}/></>:<p>No upcoming deadlines are recorded for this course.</p>}<button className="workspace-text-button" onClick={()=>setTab('assignments')}>View all assignments →</button></section><section className="portal-panel"><h3>Start a study session</h3><p>{live.guide.blurb||'Review the material from your course.'}</p>{ready.slice(0,3).map(m=><button className="portal-link-row" key={m.id} onClick={()=>dispatch({type:'openGuide',id:course.id,mode:m.id})}><span><strong>{m.label}</strong><small>{m.count}</small></span><span>→</span></button>)}{!ready.length&&<button className="workspace-text-button" onClick={()=>dispatch({type:'openUpdate',courseId:course.id,unit:null})}>Add material to create study activities</button>}</section></div></>}
 {tab==='assignments'&&<section className="portal-panel"><div className="portal-filter-row"><label className="portal-search"><input type="search" aria-label="Search course assignments" placeholder="Search assignments, exams and readings" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Assignment status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="upcoming">Upcoming</option><option value="past">Past</option><option value="completed">Completed</option><option value="all">All assignments</option></select></div><p className="portal-muted">{assignments.length} items · Open an item for its instructions, source, study plan and attached work.</p>{assignments.map(i=><DeadlineRow key={i.id} item={i} tone={standingOf(i,state.done)}/>)}{!assignments.length&&<p role="status">No assignments match this view.</p>}</section>}
 {tab==='study'&&<><section className="assignment-next"><div><strong>Create your study guide</strong><p>Choose from 11 formats, select sources, and adjust the level and length.</p></div><button className="portal-primary" onClick={()=>setStudio(true)}>Open study studio →</button></section><h3>Every way to study this course</h3><div className="portal-card-grid">{modes.map(m=><button className="portal-panel portal-mode" key={m.id} onClick={()=>dispatch({type:'openGuide',id:course.id,mode:m.id})}><strong>{m.label}</strong><p>{m.blurb}</p><span className={m.ready?'portal-tag':'portal-muted'}>{m.ready?m.count:m.missing||'Add material to get started'}</span></button>)}</div><h3>Course units</h3>{live.guide.units.map((u,index)=><button className="portal-link-row" key={`${u.name}-${index}`} onClick={()=>dispatch({type:'openGuide',id:course.id,unit:index,mode:'read'})}><span><strong>{u.name}</strong><small>{u.cards.length} cards</small></span><span>Open →</span></button>)}</>}
 {tab==='readings'&&<section className="portal-panel"><label className="portal-search"><input type="search" aria-label="Search course materials" placeholder="Search readings and uploaded material" value={query} onChange={e=>setQuery(e.target.value)}/></label><h3>Assigned readings</h3>{readingItems.filter(i=>matches(i.title)).map(i=><DeadlineRow key={i.id} item={i} tone={standingOf(i,state.done)}/>)}{!readingItems.length&&<p>No reading deadlines have been imported.</p>}<h3>Added materials</h3>{updates.filter(u=>matches(`${u.title} ${u.source}`)).map(u=><details className="portal-material" key={u.id}><summary><strong>{u.title}</strong><small>{u.source||'Added to this course'} · {u.cards.length} study cards</small></summary><p>{u.body||'This material has been organized into the course study guide.'}</p><button onClick={()=>dispatch({type:'openGuide',id:course.id,mode:'read',...(u.unit!==null?{unit:u.unit}:{})})}>Study this material →</button></details>)}{!updates.length&&<p>Add lecture notes, readings or handouts to keep them with this course.</p>}<button className="portal-primary" onClick={()=>dispatch({type:'openUpdate',courseId:course.id,unit:null})}>+ Add course material</button></section>}
 {tab==='information'&&<><div className="portal-panel"><h3>Syllabus source</h3><p>{course.source||'No syllabus source recorded.'}</p><p className="portal-muted">Assignment details contain the original syllabus quotations and available page references. Course information below includes grading, office hours, attendance and the LMS link.</p></div>{information}</>}
 </div>;
}
