import {useState} from 'react';
import {useNow,useStore} from '../state/store';
import {useDeviceLibrary} from '../lib/device-library';
import {dateToIso} from '../lib/date';
import {courseLearningInput,type LearningAttempt} from '../lib/learning-loop';
import {EMPTY_MAP,MAP_PREFIX,OWN_LABELS,STATE_WORDS,checkResult,dueByConcept,readMap,statesByConcept,checkWords,nextAction,pickCheck,type Answer,type CheckAnswer,type OwnLabel,type CheckQuestion} from '../lib/learningmap';
import {checkLengthFor} from '../lib/learningprefs';
import {useLearningPrefs} from './LearningPreferences';
/** The learning map's private store for this account and term. Read by the office-hours agenda too; written only here. */
export function useMapLibrary(){const {state,account}=useStore();return useDeviceLibrary(`${MAP_PREFIX}:${account?.id||'device'}:${state.term}`,readMap,EMPTY_MAP);}
export function LearningMap(){const {state,account}=useStore();return <MapBody key={`${account?.id||'device'}:${state.term}`}/>;}
function MapBody(){
 const {state,dispatch,catalog}=useStore();const now=useNow();const lib=useMapLibrary();const prefs=useLearningPrefs().value;
 const [chosenCourse,setCourseId]=useState('');const courseId=chosenCourse||catalog.courses[0]?.id||'';
 const [run,setRun]=useState<{picks:CheckQuestion[];at:number;shown:boolean;answers:CheckAnswer[]}|null>(null);
 const [name,setName]=useState('');const [note,setNote]=useState('');const [label,setLabel]=useState<OwnLabel>('Not started');const [asQuestion,setAsQuestion]=useState(false);const [notice,setNotice]=useState('');
 const guide=catalog.guides[courseId];const saved=lib.value.checks[courseId];
 const dues=guide?dueByConcept(courseId,guide,state.reviews,now.getTime()):{};const due=Object.values(dues).reduce((a,b)=>a+b,0);
 const input=guide?courseLearningInput(courseId,guide,state.reviews,{due,now:now.getTime()}):null;
 /* A saved check only shapes the map when the student said it may. */
 const withCheck=input&&saved?.useInPlan?{...input,attempts:[...input.attempts,...saved.answers.map((a):LearningAttempt=>({conceptId:a.conceptId,correct:a.answer==='got',kind:'diagnostic',source:'Start Here Check'}))]}:input;
 const states=withCheck?statesByConcept(withCheck,dues):[];
 const sourceOf=(id:string)=>input?.concepts.find(c=>c.id===id)?.source??'';
 const mine=lib.value.own.filter(o=>o.courseId===courseId);
 const length=checkLengthFor(prefs.session);
 const finish=(answers:CheckAnswer[])=>{lib.update(old=>({...old,checks:{...old.checks,[courseId]:{at:dateToIso(now),answers,useInPlan:false}}}));setRun(null);};
 const answer=(a:Answer)=>{if(!run)return;const answers=[...run.answers,{conceptId:run.picks[run.answers.length].conceptId,answer:a}];if(answers.length>=run.picks.length)finish(answers);else setRun({...run,answers,shown:false});};
 const result=saved&&input?checkResult(input.concepts,saved.answers):null;
 /* `portal-workspace` for the classless buttons, as on the study journal. */
 return <details className="portal-workspace portal-panel learning-map"><summary>Learning map &amp; start-here check{states.filter(s=>s.state==='needs-review').length>0?` · ${states.filter(s=>s.state==='needs-review').length} to review`:''}</summary><p>Your course as concepts, where the evidence stands on each, and one next step. States describe evidence, not you, and stay on this device.</p><label>Course<select className="input" value={courseId} onChange={e=>{setCourseId(e.target.value);setRun(null);}}>{catalog.courses.map(c=><option key={c.id} value={c.id}>{c.code}</option>)}</select></label>
 <section className="portal-panel"><span className="portal-eyebrow">Start here check</span>{run?<><p>Question {run.answers.length+1} of {run.picks.length} · “Not sure” is always a fine answer.</p><h3>{run.picks[run.answers.length].card.q}</h3>{run.shown?<><blockquote>{run.picks[run.answers.length].card.a}</blockquote><div className="portal-actions"><button onClick={()=>answer('got')}>I knew it</button><button onClick={()=>answer('unsure')}>Not sure</button><button onClick={()=>answer('missed')}>I missed it</button></div></>:<div className="portal-actions"><button onClick={()=>setRun({...run,shown:true})}>Show the answer</button><button onClick={()=>setRun(null)}>Stop</button></div>}</>:<><p>{guide&&guide.units.some(u=>u.cards.length>0)?`A short, ungraded check from this course’s own cards — up to ${length} questions, sized to your ${prefs.session}-minute sitting. It suggests what to practice; it is not a grade or a record.`:'This course has no cards to check against yet.'}</p><div className="portal-actions"><button disabled={!guide||!guide.units.some(u=>u.cards.length>0)} onClick={()=>guide&&setRun({picks:pickCheck(courseId,guide,length),at:now.getTime(),shown:false,answers:[]})}>{saved?'Take it again':'Start the check'}</button></div></>}{result&&!run&&<><ul>{checkWords(result).map(l=><li key={l}>{l}</li>)}</ul><label><input type="checkbox" checked={saved.useInPlan} onChange={e=>lib.update(old=>({...old,checks:{...old.checks,[courseId]:{...old.checks[courseId],useInPlan:e.target.checked}}}))}/> Let this result shape my map and study plan</label><div className="portal-actions"><button onClick={()=>lib.update(old=>{const {[courseId]:_gone,...rest}=old.checks;return {...old,checks:rest};})}>Delete this result</button></div></>}</section>
 <section className="portal-panel"><span className="portal-eyebrow">Concepts in this course</span>{states.length===0?<p>No concepts for this course yet.</p>:states.map(s=>{const next=nextAction(s,(dues[s.id]??0)>0);const asked=mine.some(o=>o.question&&o.name===s.name);return <article className="study-journal-entry" key={s.id}><span className="portal-eyebrow">{STATE_WORDS[s.state]}</span><h3>{s.name}</h3><p>Source: {sourceOf(s.id)}</p>{prefs.density!=='concise'&&<p>{s.evidence.length} evidence {s.evidence.length===1?'record':'records'}{s.nextReview?` · next review ${s.nextReview}`:''}</p>}{prefs.density==='expanded'&&s.evidence.length>0&&<ul>{s.evidence.map((e,i)=><li key={i}>{e.label} — {e.source}</li>)}</ul>}<p>Next: {next.text}. <span className="portal-muted">{next.why}</span></p><div className="portal-actions"><button onClick={()=>{const from=`learning-map:${s.id}`;if(state.tasks.some(t=>t.from===from)){setNotice('That step is already on your plan.');return;}dispatch({type:'addTask',task:{title:next.text,date:null,time:'',note:next.why,courseId,from}});setNotice('Added to your plan. Set a date in Actions.');}}>Add this step to my plan</button><button disabled={asked} onClick={()=>lib.update(old=>({...old,own:[{id:crypto.randomUUID(),courseId,name:s.name,note:'',label:'Not started' as OwnLabel,question:true},...old.own]}))}>{asked?'Saved as a private question':'I don’t understand this'}</button></div></article>;})}</section>
 <section className="portal-panel"><span className="portal-eyebrow">Your own concepts and questions</span><p>Add anything you want to keep track of. Only you see these.</p><form onSubmit={e=>{e.preventDefault();if(lib.update(old=>({...old,own:[{id:crypto.randomUUID(),courseId,name,note,label,question:asQuestion},...old.own]}))){setName('');setNote('');setLabel('Not started');setAsQuestion(false);}}}><div className="study-controls"><label>Concept or question<input className="input" required maxLength={500} value={name} onChange={e=>setName(e.target.value)}/></label><label>Where you stand<select className="input" value={label} onChange={e=>setLabel(e.target.value as OwnLabel)}>{OWN_LABELS.map(l=><option key={l}>{l}</option>)}</select></label></div><label>Notes<textarea className="input" maxLength={4000} value={note} onChange={e=>setNote(e.target.value)}/></label><label><input type="checkbox" checked={asQuestion} onChange={e=>setAsQuestion(e.target.checked)}/> This is a question I need help with</label><button disabled={lib.blocked||!courseId} className="portal-primary">Add to my map</button></form>{mine.map(o=><article className="study-journal-entry" key={o.id}><span className="portal-eyebrow">{o.question?'Private question':'Your concept'} · {o.label}</span><h3>{o.name}</h3>{o.note&&<p className="preserve-lines">{o.note}</p>}<div className="portal-actions"><label>Where you stand<select className="input" value={o.label} onChange={e=>lib.update(old=>({...old,own:old.own.map(x=>x.id===o.id?{...x,label:e.target.value as OwnLabel}:x)}))}>{OWN_LABELS.map(l=><option key={l}>{l}</option>)}</select></label><button onClick={()=>lib.update(old=>({...old,own:old.own.map(x=>x.id===o.id?{...x,question:!x.question}:x)}))}>{o.question?'Not a question':'Mark as a question I need help with'}</button><button onClick={()=>lib.update(old=>({...old,own:old.own.filter(x=>x.id!==o.id)}))}>Delete</button></div></article>)}</section>
 {(notice||lib.error)&&<p role="status">{lib.error||notice}</p>}</details>;
}
