/**
 * The installed icons, as text.
 *
 * `public/icon.svg` and `public/icon-maskable.svg` are committed rather than
 * built — a browser and an OS installer fetch them straight off the origin,
 * with no bundler in the path — and they are written from here by
 * `scripts/icons.mjs`. `mark.test.ts` compares what is on disk against what
 * this module produces, so a hand-edited icon fails rather than quietly
 * becoming a second, slightly different logo.
 *
 * It lives beside the drawing rather than inside the script for one reason
 * worth recording: the test used to import the script, and importing the
 * script *wrote the files* before the assertion read them — so the guard
 * against a hand-edited icon repaired the edit and reported green. That was
 * found by breaking the icon on purpose and watching the test pass. The
 * script is now I/O only and has nothing to import.
 *
 * This is in `src/` and is not part of the app: nothing the app renders
 * imports it, so it never reaches a bundle. Same arrangement as
 * `styles/rules.ts`, which the linter reads and the app does not.
 */

// The extension is not optional here. Node runs this file directly, from
// `scripts/icons.mjs`, and its TypeScript stripping resolves like ESM: no
// extension, no module. `allowImportingTsExtensions` in `tsconfig.app.json`
// is what makes the same spelling legal to the compiler.
import { BARS, GRID, RADIUS, edgePath, facePath, type Bar } from './mark.data.ts';

/*
 * The two gradients, and why they are spelled out rather than read from
 * `--chrome`.
 *
 * `app.css` carries the app's brushed metal and `lib/look.ts` inverts it on a
 * light ground — both of which are about type on a surface whose colour the
 * student chose. A home-screen tile has no ground and no student: it is
 * painted once, on black, by whatever launcher installed it. So the metal is
 * fixed here, cut through the same band as `--chrome` so the tile and the
 * app's display type are recognisably the same material.
 */
const FACE_STOPS: [number, string][] = [
  [0, '#ffffff'],
  [20, '#eef1f6'],
  [40, '#a7aeba'],
  [50, '#7f8693'],
  [58, '#b9c0cb'],
  [80, '#f4f6fa'],
  [100, '#a3aab6'],
];

/** The turned edge: the same sweep, darker, so the fold reads as a fold. */
const EDGE_STOPS: [number, string][] = [
  [0, '#b9c0cb'],
  [40, '#666c77'],
  [72, '#868d9a'],
  [100, '#555b65'],
];

/** The ground, which is `background_color` in the manifest. */
const GROUND = '#0a0b0e';

/**
 * How far the maskable icon's mark is pulled in.
 *
 * 0.82 rather than the 0.8 the spec's safe zone implies: the safe zone is a
 * circle of 80% *diameter*, and the mark is measured to its corners, which sit
 * further from the centre than its edges do. `mark.test.ts` checks the scale
 * against the real half-diagonal rather than trusting this comment.
 */
export const MASK_SCALE = 0.82;

const stops = (list: [number, string][]) =>
  list.map(([at, color]) => `      <stop offset="${at}%" stop-color="${color}" />`).join('\n');

const defs = () => `  <defs>
    <linearGradient id="face" x1="0.08" y1="0" x2="0.42" y2="1">
${stops(FACE_STOPS)}
    </linearGradient>
    <linearGradient id="edge" x1="0" y1="0" x2="0.2" y2="1">
${stops(EDGE_STOPS)}
    </linearGradient>
  </defs>`;

/** The three slabs, each as a lit face and a turned edge. */
const slabs = () =>
  BARS.map(
    (bar: Bar) =>
      `    <path d="${facePath(bar)}" fill="url(#face)" />\n` +
      `    <path d="${edgePath(bar)}" fill="url(#edge)" />`,
  ).join('\n');

const HEAD = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${GRID} ${GRID}" width="${GRID}" height="${GRID}">`;
const WRITTEN = '  <!-- Generated by scripts/icons.mjs from src/components/mark.data.ts. Do not edit. -->';

/** The tile as the logo is drawn: rounded, the way a launcher shows it. */
const icon = () => `${HEAD}
${WRITTEN}
${defs()}
  <rect width="${GRID}" height="${GRID}" rx="${RADIUS}" fill="${GROUND}" />
  <g>
${slabs()}
  </g>
</svg>
`;

/*
 * The maskable slot. Android and Windows crop an icon to whatever shape the
 * launcher uses, so the ground runs square to the edges — a rounded tile
 * inside a circular crop is a black tile with four pale nicks in it — and the
 * mark is pulled in to sit inside the safe circle.
 */
const maskable = () => {
  const c = GRID / 2;
  return `${HEAD}
${WRITTEN}
${defs()}
  <rect width="${GRID}" height="${GRID}" fill="${GROUND}" />
  <g transform="translate(${c} ${c}) scale(${MASK_SCALE}) translate(${-c} ${-c})">
${slabs()}
  </g>
</svg>
`;
};

/** The tile iOS masks itself: square to the edges, and no rounding of ours. */
export const APPLE = `${HEAD}
${defs()}
  <rect width="${GRID}" height="${GRID}" fill="${GROUND}" />
  <g>
${slabs()}
  </g>
</svg>
`;

/** What belongs in `public/`, by name. */
export const FILES: Record<string, string> = {
  'icon.svg': icon(),
  'icon-maskable.svg': maskable(),
};
