import { FilePick } from './ui';
import {useState} from 'react';
import {useDeviceLibrary} from '../lib/device-library';
import {EMPTY_REGISTRATION,readRegistration,type RegistrationData as Stored} from '../lib/portal-storage';
import {parseCatalog,conflicts,clock24,CATALOG_TEMPLATE,type CatalogCourse} from '../lib/registration';
import {download} from '../lib/deliver';
const KEY='semester.registration.v1';
const DAYS=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const meetLine=(c:CatalogCourse)=>c.meetings.map(m=>`${m.days.map(d=>DAYS[d]).join('/')} ${clock24(m.start)}–${clock24(m.end)}`).join(' · ')||'Meeting time not provided';
export function RegistrationPortal(){
 const library=useDeviceLibrary(KEY,readRegistration,EMPTY_REGISTRATION);const data=library.value;const setData=library.update;const [undo,setUndo]=useState<Stored|null>(null);const [tab,setTab]=useState('catalog');const [query,setQuery]=useState('');const [term,setTerm]=useState('');const [dept,setDept]=useState('');const [openOnly,setOpenOnly]=useState(false);const [detail,setDetail]=useState<string|null>(null);const [message,setMessage]=useState('');const [name,setName]=useState('');

 const all=data.catalog?.courses||[],cart=all.filter(c=>data.cart.includes(c.id));const problems=conflicts(cart);const terms=[...new Set(all.map(c=>c.term))];const activeTerm=term||terms[0]||'';
 const shown=all.filter(c=>c.term===activeTerm&&(!dept||c.department===dept)&&(!openOnly||c.seats!==null&&c.seats>0)&&`${c.code} ${c.title} ${c.instructor} ${c.description}`.toLowerCase().includes(query.toLowerCase()));
 const selected=all.find(c=>c.id===detail);const toggle=(id:string)=>setData(d=>({...d,cart:d.cart.includes(id)?d.cart.filter(x=>x!==id):[...d.cart,id]}));
 const upload=async(f:File)=>{try{if(f.size>2_000_000)throw new Error('Use a file smaller than 2 MB.');const catalog=parseCatalog(await f.text());if(!setData(d=>({...d,catalog,cart:d.cart.filter(id=>catalog.courses.some(c=>c.id===id))})))return;setTerm(catalog.courses[0].term);setDept('');setDetail(null);setMessage(`Imported ${catalog.courses.length} sections from ${catalog.institution}. Seat counts reflect this file, not live availability.`);}catch(e){setMessage(e instanceof Error?e.message:'Unable to import catalog.');}};
 const save=()=>{if(!name.trim()||!cart.length)return;if(data.plans.length>=12){setMessage('You have 12 saved schedules. Export a backup and remove an older schedule before adding another.');return;}if(!setData(d=>({...d,plans:[...d.plans,{id:crypto.randomUUID(),name:name.trim(),courses:cart}]})))return;setName('');setMessage('Potential schedule saved. No enrollment was submitted.');};
 return <div className="registration-portal"><header className="portal-banner"><div><span className="portal-eyebrow">Academic planning</span><h2>Find your next semester</h2><p>Explore classes, compare schedules and keep your registration cart in one place.</p></div><FilePick block={false} multiple={false} accept=".json,.csv,text/csv,application/json" onPick={files=>{if(files[0])void upload(files[0]);}}>Import course catalog</FilePick></header>
 <>{library.error&&<p role="alert" className="portal-warning">{library.error}<button onClick={()=>download({name:'Semester registration recovery.json',body:library.recovery(),mime:'application/json'})}>Download recovery copy</button></p>}</><div className="portal-notice">{data.catalog?`${data.catalog.institution} · ${all.length} sections · imported ${new Date(data.catalog.importedAt).toLocaleDateString()}`:'Your institution can supply its course catalog as JSON or CSV.'} <strong>Planning workspace</strong> · Official enrollment and live seats require an institution connection.</div>
 <div className="portal-tabs" role="tablist" aria-label="Registration workspace">{[['catalog','Course search'],['cart',`Cart (${cart.length})`],['plans',`Potential schedules (${data.plans.length})`]].map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {message&&<p className="portal-notice" role="status">{message}{undo&&<button onClick={()=>{if(!setData(undo))return;setUndo(null);setMessage('Previous catalog restored.');}}>Undo removal</button>}</p>}
 {tab==='catalog'&&<><div className="portal-filter-row"><label className="portal-search"><input type="search" aria-label="Search course catalog" placeholder="Search classes, instructors or keywords" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Catalog term" value={activeTerm} onChange={e=>{setTerm(e.target.value);setDept('');}}><option value="" disabled>Select term</option>{terms.map(t=><option key={t}>{t}</option>)}</select><select aria-label="Course department" value={dept} onChange={e=>setDept(e.target.value)}><option value="">All departments</option>{[...new Set(all.filter(c=>c.term===activeTerm).map(c=>c.department))].map(d=><option key={d}>{d}</option>)}</select><label className="portal-check"><input type="checkbox" checked={openOnly} onChange={e=>setOpenOnly(e.target.checked)}/>Reported open seats</label></div>
 {!all.length?<section className="portal-empty"><div className="portal-empty-icon">▦</div><h3>Start with your school’s course catalog</h3><p>Import the subjects, sections, credits, instructors and meeting times your school provides. You can then build and compare schedules.</p><FilePick block={false} multiple={false} accept=".json,.csv" onPick={files=>{if(files[0])void upload(files[0]);}}>Import catalog</FilePick><button onClick={()=>download({name:'Semester course catalog template.json',body:JSON.stringify(CATALOG_TEMPLATE,null,2),mime:'application/json'})}>Download institution template</button><details><summary>CSV format</summary><p>Columns: code, section, title, term, department, credits, instructor, location, description, prerequisites, seats, days, start, end. Days use numbers 0–6; quote multiple days, for example “1,3,5”. Times use HH:MM. JSON supports multiple meetings per section.</p></details></section>:<div className="registration-results"><section><p className="portal-muted">{shown.length} sections found</p>{shown.slice(0,150).map(c=><article key={c.id} className={`portal-course-result ${detail===c.id?'is-selected':''}`}><button className="portal-course-description" onClick={()=>setDetail(c.id)}><span className="portal-eyebrow">{c.code} · Section {c.section}</span><h3>{c.title}</h3><p>{c.instructor||'Instructor to be announced'} · {c.credits} credits</p><p>{meetLine(c)}</p><span className="portal-tag">{c.seats===null?'Seats not provided':c.seats===0?'Reported closed':`${c.seats} reported seats`}</span></button><button aria-label={`${data.cart.includes(c.id)?'Remove':'Add'} ${c.code} section ${c.section} ${data.cart.includes(c.id)?'from':'to'} cart`} onClick={()=>toggle(c.id)}>{data.cart.includes(c.id)?'✓ In cart':'+ Add to cart'}</button></article>)}{shown.length>150&&<p>Narrow your search to see more sections.</p>}{!shown.length&&<p role="status">No classes match these filters.</p>}</section><aside className="portal-panel registration-detail">{selected?<><span className="portal-eyebrow">Course information</span><h3>{selected.code} · {selected.title}</h3><p>{selected.description||'Description not supplied in this catalog.'}</p><dl><dt>Section / credits</dt><dd>{selected.section} / {selected.credits}</dd><dt>Instructor</dt><dd>{selected.instructor||'Not supplied'}</dd><dt>Schedule</dt><dd>{meetLine(selected)}</dd><dt>Location</dt><dd>{selected.location||'Not supplied'}</dd><dt>Prerequisites</dt><dd>{selected.prerequisites||'Not supplied — check with your institution'}</dd></dl><button className="portal-primary" onClick={()=>toggle(selected.id)}>{data.cart.includes(selected.id)?'Remove from cart':'Add to registration cart'}</button></>:<><h3>Get to know a class</h3><p>Select a section to see its description, prerequisites, instructor and meeting times.</p></>}</aside></div>}</>}
 {tab==='cart'&&<><div className="portal-stats"><div><strong>{cart.length}</strong><span>Sections in cart</span></div><div><strong>{cart.reduce((sum,c)=>sum+c.credits,0)}</strong><span>Planned credits</span></div><div><strong>{problems.length}</strong><span>Time conflicts</span></div></div>{cart.length?<><section className="portal-panel"><h3>Review your selections</h3>{cart.map(c=><div className="portal-link-row" key={c.id}><span><strong>{c.code} · {c.title}</strong><small>{c.term} · {meetLine(c)}</small></span><button onClick={()=>toggle(c.id)} aria-label={`Remove ${c.code} from cart`}>Remove</button></div>)}{problems.map((p,i)=><p key={i} className="portal-warning">{p.a.code} and {p.b.code} overlap on {p.days.map(d=>DAYS[d]).join(', ')}.</p>)}{cart.some(c=>cart.some(other=>other.id!==c.id&&other.code===c.code&&other.term===c.term))&&<p className="portal-warning">Multiple sections of the same course are in this cart. Choose the section you intend to take.</p>}{cart.some(c=>!c.meetings.length)&&<p className="portal-warning">Some meeting times are missing. Conflicts cannot be checked for those sections.</p>}<div className="portal-filter-row"><input className="input" aria-label="Potential schedule name" placeholder="Name this potential schedule" value={name} onChange={e=>setName(e.target.value)} maxLength={80}/><button className="portal-primary" disabled={!name.trim()} onClick={save}>Save potential schedule</button><button onClick={()=>download({name:'Semester registration plan.json',body:JSON.stringify({status:'planning-only',institution:data.catalog?.institution,courses:cart},null,2),mime:'application/json'})}>Export cart</button></div></section><Schedule courses={cart}/></>:<section className="portal-empty"><h3>Your cart is ready for ideas</h3><button onClick={()=>setTab('catalog')}>Find a class →</button></section>}</>}
 {tab==='plans'&&<>{data.plans.length?<div className="portal-card-grid">{data.plans.map(p=><section className="portal-panel" key={p.id}><h3>{p.name}</h3><p>{p.courses.length} sections · {p.courses.reduce((s,c)=>s+c.credits,0)} credits · {conflicts(p.courses).length} time conflicts</p>{p.courses.map(c=><p key={c.id}><strong>{c.code}</strong> · {c.title}<small className="portal-block">{c.term} · {meetLine(c)}</small></p>)}<details><summary>View weekly schedule</summary><Schedule courses={p.courses}/></details><div className="portal-actions"><button onClick={()=>{const ids=p.courses.map(c=>c.id).filter(id=>all.some(c=>c.id===id));if(!setData(d=>({...d,cart:ids})))return;setTab('cart');setMessage(ids.length===p.courses.length?'Schedule loaded into cart.':`${p.courses.length-ids.length} sections are no longer in the current catalog; review your cart.`);}}>Load into cart</button><button aria-label={`Delete potential schedule ${p.name}`} onClick={()=>setData(d=>({...d,plans:d.plans.filter(x=>x.id!==p.id)}))}>Delete</button></div></section>)}</div>:<section className="portal-empty"><h3>Compare a few possibilities</h3><p>Add classes to your cart and save it with a name. Each saved option keeps its own course details.</p><button onClick={()=>setTab('cart')}>Open cart →</button></section>}</>}
 <details className="portal-import-help"><summary>Institution catalog format and data updates</summary>{data.catalog&&<button onClick={()=>{if(!setData(d=>({...d,catalog:null,cart:[]})))return;setUndo(data);setMessage('Imported catalog removed. Saved potential schedules are retained.');}}>Remove imported catalog</button>}<p>Importing a new catalog replaces the local catalog. Cart entries that still exist are retained; saved potential schedules retain their previous snapshot. Imported seat counts and prerequisites are information to review with your registrar.</p><button onClick={()=>download({name:'Semester course catalog template.json',body:JSON.stringify(CATALOG_TEMPLATE,null,2),mime:'application/json'})}>Download catalog template</button></details>
 </div>;
}
function Schedule({courses}:{courses:CatalogCourse[]}){const terms=[...new Set(courses.map(c=>c.term))];return <div className="schedule-preview">{terms.map(term=><section key={term}><h3>{term} · Weekly schedule</h3><div className="schedule-week">{[1,2,3,4,5,6,0].map(day=><div className="schedule-day" key={day}><h4>{DAYS[day]}</h4>{courses.filter(c=>c.term===term).flatMap(c=>c.meetings.filter(m=>m.days.includes(day)).map((m,i)=>({c,m,i}))).sort((a,b)=>a.m.start-b.m.start).map(({c,m,i})=><div className="schedule-block" key={`${c.id}-${i}`}><strong>{c.code}</strong><span>{clock24(m.start)}–{clock24(m.end)}</span><small>{c.location||'Location not supplied'}</small></div>)}</div>)}</div></section>)}</div>;}
