import {addFile,listFiles,getFile,openFile,onFilesChanged,type Settled} from '../lib/files';
import { FilePick } from './ui';
import { useEffect, useRef, useState } from 'react';
import { useNow, useStore } from '../state/store';
import { useLive } from '../lib/live';
import { ask } from '../lib/claude';
import { configured, routeLabel } from '../lib/assistant';
import { extractText } from '../lib/extract';
import { useDraft } from '../lib/draft.hook';
import { fromMarkdown } from '../lib/document';
import { STUDY_FORMATS, STUDY_SYSTEM, citationLocation, parseStudySections, quoteContext, studyPrompt, studyMarkdown, studySources, type StudyFormat, type StudySection, type StudySource, type StudioControls } from '../lib/studystudio';
import { Drawing } from './Drawing';
import { MasteryGraph } from './MasteryGraph';
import { courseLearningInput, learningState, readinessForecast } from '../lib/learning-loop';
import { cardIdentity, comeRound } from '../lib/review';

const INITIAL:StudioControls={length:'Standard',difficulty:'Course level',readingLevel:'Plain language',questions:10,questionTypes:['Multiple choice','Short answer'],minutes:25,examDate:'',topics:'',weaknesses:'',answers:'At the end'};

export function StudyStudio({courseId,onClose}:{courseId:string;onClose:()=>void}) {
 const {state,dispatch,catalog}=useStore();const {guide}=useLive(courseId);const course=catalog.byId[courseId];
 const now=useNow();
 const [formats,setFormats]=useState<StudyFormat[]>(['comprehensive']);const [controls,setControls]=useState<StudioControls>(INITIAL);
 const [selected,setSelected]=useState<string[]>([]);const [uploads,setUploads]=useState<StudySource[]>([]);const [paste,setPaste]=useState('');const [pasteName,setPasteName]=useState('Pasted material');
 const [sections,setSections]=useState<StudySection[]>([]);const [usedSources,setUsedSources]=useState<StudySource[]>([]);const [sourceOpen,setSourceOpen]=useState<string|null>(null);
 const [consent,setConsent]=useState(false);const [policyOk,setPolicyOk]=useState(false);const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');
 const abort=useRef<AbortController|null>(null);const draft=useDraft('study-studio','guide',`${state.term}:${courseId}`);
 const [savedFiles,setSavedFiles]=useState<Settled[]>([]);
 useEffect(()=>{let alive=true;const refresh=()=>{void listFiles().then(fs=>{if(alive)setSavedFiles(fs.filter(f=>f.courseId===courseId));});};refresh();const unsubscribe=onFilesChanged(refresh);return()=>{alive=false;unsubscribe();};},[courseId]);
 const policy=course?.ai;const banned=policy?.stance==='banned';
 const learningInput=courseLearningInput(courseId,guide,state.reviews,{due:comeRound(guide.units.flatMap(unit=>unit.cards.map(card=>cardIdentity(courseId,card))),state.reviews,now.getTime())});
 const conceptStates=learningState(learningInput);const readiness=readinessForecast(learningInput,now);
 useEffect(()=>()=>{abort.current?.abort();if('speechSynthesis' in window)window.speechSynthesis.cancel();},[]);
 // `lib/studystudio.ts`, so the list a lecture transcript has to appear in is
 // somewhere a test can reach. See `studySources` for the chain it stands at
 // the end of.
 const sources:StudySource[]=studySources(courseId,guide.units,state.updates,state.notes,uploads);
 const chosen=sources.filter(s=>selected.includes(s.id));
 const canRegenerate=chosen.length===usedSources.length&&chosen.every(s=>usedSources.some(u=>u.id===s.id&&u.text===s.text));
 const change=<K extends keyof StudioControls>(key:K,value:StudioControls[K])=>setControls(c=>({...c,[key]:value}));
 const commit=(next:StudySection[],refs:StudySource[])=>{const body=studyMarkdown(next,refs);if(body.length>95000)throw new Error('This guide is too large to save. Choose fewer formats or shorter sections.');setSections(next);setUsedSources(refs);draft.set(body);};
 const generate=async(one?:StudySection)=>{
  if(busy||!configured()||banned||!consent||(!policyOk&&policy?.stance!=='allowed'))return;
  if(one&&!canRegenerate){setNotice('Select the original source set to regenerate a section.');return;}
  const refs=one?usedSources:chosen;const requested=one?[one.format]:formats;
  let prompt:string;try{prompt=studyPrompt(requested,controls,refs,`${policy?.stance??'unstated'}: ${policy?.note??'No policy recorded; student confirmed permitted study use.'}`);}catch(e){setNotice((e as Error).message);return;}
  setBusy(one?one.id:'all');setNotice('');abort.current=new AbortController();
  try{
   const text=await ask({
    about: 'study studio',system:STUDY_SYSTEM,messages:[{role:'user',content:prompt+(one?`\nRegenerate only the section titled ${JSON.stringify(one.title)}. Return exactly one section.`:'')}],maxTokens:12000,
    courseId: courseId,signal:abort.current.signal});
   const parsed=parseStudySections(text,refs,requested);
   if(one&&parsed.length!==1)throw new Error('The response contained more than the selected section. Your existing sections are unchanged.');
   if(one)commit(sections.map(s=>s.id===one.id?{...parsed[0],id:s.id}:s),refs);else {
    if(draft.value.trim())dispatch({type:'makeDocument',doc:{title:`${course?.code??guide.code} · Previous study draft`,subtitle:'Earlier draft saved before regeneration',courseId,blocks:fromMarkdown(draft.value)}});
    commit(parsed,refs);
   }
   setNotice('Study draft created. Source quotations were matched to the selected text. Review the AI explanations before using them.');
  }catch(e){setNotice(e instanceof Error&&e.name==='AbortError'?'Generation canceled. Your existing guide is unchanged.':(e as Error).message);}finally{setBusy('');}
 };
 const upload=async(file:File,existingId?:string)=>{
  if(file.size>20_000_000){setNotice('Choose a file smaller than 20 MB.');return;}setBusy('reading');setNotice('Reading material…');
  try{const got=await extractText(file);if(!got.text.trim())throw new Error('No selectable text found. Paste a readable excerpt or use the course import tool for scanned material.');const saved=existingId||((await addFile(file,courseId)).id);const prefix=saved;const next:StudySource[]=got.pages?.length?got.pages.filter(p=>p.text.trim()).map(p=>({id:`upload-${prefix}-${p.page}`,title:got.name,fileId:saved,text:p.text,locator:`${/\.pptx$/i.test(file.name)?'Slide':'Page'} ${p.page}`})):[{id:`upload-${prefix}`,title:got.name,fileId:saved,text:got.text,locator:'Uploaded text; page not recorded'}];setUploads(s=>[...s.filter(x=>x.fileId!==saved),...next]);setSelected(s=>[...new Set([...s,...next.map(n=>n.id)])]);setNotice(`${next.length} source excerpts added. Review the selection before generating.`);}catch(e){setNotice((e as Error).message);}finally{setBusy('');}
 };
 const save=()=>{if(!draft.value.trim())return;dispatch({type:'makeDocument',open:true,doc:{title:`${course?.code??guide.code} · Study guide`,subtitle:'AI-assisted study draft · Review explanations against the cited material',courseId,blocks:fromMarkdown(draft.value)}});draft.done();};
 const speak=(text:string)=>{if(!('speechSynthesis' in window)){setNotice('Read-aloud is not supported by this browser.');return;}window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(text.replace(/[#*`]/g,'')));};
 return <div className="study-studio portal-workspace"><div className="portal-heading"><div><span className="portal-eyebrow">{course?.code} · {state.sample?'Sample material':'Course study workspace'}</span><h2>Make a guide that fits how you study</h2><p>Choose your material and one or more formats. Save the result with your course.</p></div><button onClick={onClose}>← Back to study</button></div>
  <section className="portal-panel"><h3>Learning evidence</h3><p className="portal-muted">Readiness range {readiness.range[0]}–{readiness.range[1]}%, not a grade. Unanswered concepts stay unmeasured.</p><MasteryGraph concepts={conceptStates}/></section>
  <div className="study-studio-columns"><section className="portal-panel"><h3>1. Choose source material</h3><p className="portal-muted">Only checked text is sent. Personal notes are excluded until you select them.</p><fieldset disabled={!!busy} className="study-source-list">{sources.map(s=><label key={s.id}><input type="checkbox" aria-label={s.title} checked={selected.includes(s.id)} onChange={e=>{setSelected(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id));setConsent(false);}}/><span><strong>{s.title}</strong><small>{s.locator} · {s.text.length.toLocaleString()} characters</small></span><button type="button" onClick={()=>setSourceOpen(sourceOpen===s.id?null:s.id)} aria-label={`Preview source ${s.title}`}>Preview</button></label>)}{!sources.length&&<p>Add a file or paste material to begin.</p>}</fieldset>{sourceOpen&&<details open className="study-source-preview"><summary>{sources.find(s=>s.id===sourceOpen)?.title}</summary><pre>{sources.find(s=>s.id===sourceOpen)?.text}</pre></details>}
  <details className="study-saved-files"><summary>Reuse a saved course file ({savedFiles.length})</summary><p>Open the original or add its readable text without uploading it again.</p>{savedFiles.map(f=><div key={f.id}><strong>{f.name}</strong><div className="portal-actions"><button disabled={!!busy} onClick={async()=>{const original=await getFile(f.id);if(original){setConsent(false);void upload(new File([original.blob],original.name,{type:original.type}),f.id);}}}>Use as source</button><button onClick={()=>void openFile(f.id)}>Open original</button></div></div>)}</details><FilePick multiple={false} accept=".pdf,.docx,.pptx,.txt,.md,.rtf" disabled={!!busy} onPick={files=>{if(files[0])void upload(files[0]);setConsent(false);}}>Add a source file</FilePick><details><summary>Paste material</summary><label>Source title<input value={pasteName} onChange={e=>setPasteName(e.target.value)} maxLength={160}/></label><label>Source text<textarea rows={5} value={paste} onChange={e=>setPaste(e.target.value)} maxLength={80000}/></label><button disabled={!paste.trim()||!!busy} onClick={()=>{const id=`paste-${crypto.randomUUID()}`;setUploads(s=>[...s,{id,title:pasteName.trim()||'Pasted material',text:paste,locator:'Pasted text; page not recorded'}]);setSelected(s=>[...s,id]);setPaste('');setConsent(false);}}>Add this source</button></details><p>{chosen.length} selected · {chosen.reduce((n,s)=>n+s.text.length,0).toLocaleString()} / 80,000 characters per request</p></section>
  <section className="portal-panel"><h3>2. Choose your formats</h3><fieldset disabled={!!busy} className="study-format-list">{STUDY_FORMATS.map(([id,title,detail])=><label key={id}><input type="checkbox" checked={formats.includes(id)} onChange={e=>setFormats(f=>e.target.checked?[...f,id]:f.filter(x=>x!==id))}/><span><strong>{title}</strong><small>{detail.replace(' as a Mermaid flowchart in the diagram field, with a text explanation in body','')}</small></span></label>)}</fieldset></section></div>
  <section className="portal-panel"><h3>3. Adjust your guide</h3><fieldset disabled={!!busy} className="study-controls"><label>Length<select value={controls.length} onChange={e=>change('length',e.target.value)}>{['Short','Standard','Detailed'].map(x=><option key={x}>{x}</option>)}</select></label><label>Difficulty<select value={controls.difficulty} onChange={e=>change('difficulty',e.target.value)}>{['Foundations','Course level','Challenge'].map(x=><option key={x}>{x}</option>)}</select></label><label>Reading level<select value={controls.readingLevel} onChange={e=>change('readingLevel',e.target.value)}>{['Plain language','College level','Technical'].map(x=><option key={x}>{x}</option>)}</select></label><label>Number of questions<input type="number" min={1} max={50} value={controls.questions} onChange={e=>change('questions',Math.max(1,Math.min(50,Number(e.target.value)||1)))}/></label><label>Study time (minutes)<input type="number" min={5} max={240} value={controls.minutes} onChange={e=>change('minutes',Math.max(5,Math.min(240,Number(e.target.value)||5)))}/></label><label>Exam date (optional)<input type="date" value={controls.examDate} onChange={e=>change('examDate',e.target.value)}/></label><label>Answer placement<select value={controls.answers} onChange={e=>change('answers',e.target.value)}><option>At the end</option><option>After each question</option></select></label><label>Topics<input value={controls.topics} onChange={e=>change('topics',e.target.value)} placeholder="Optional topic focus" maxLength={1000}/></label><label>Areas to practise<input value={controls.weaknesses} onChange={e=>change('weaknesses',e.target.value)} placeholder="What feels unclear?" maxLength={1000}/></label></fieldset><fieldset className="study-question-types" disabled={!!busy}><legend>Question types</legend>{['Multiple choice','True or false','Matching','Short answer','Numerical'].map(type=><label key={type}><input type="checkbox" checked={controls.questionTypes.includes(type)} onChange={e=>change('questionTypes',e.target.checked?[...controls.questionTypes,type]:controls.questionTypes.filter(t=>t!==type))}/>{type}</label>)}</fieldset>
  <div className="study-generation"><p>Course AI policy: <strong>{policy?.stance??'Not recorded'}</strong>{policy?.note?` · ${policy.note}`:''}</p>{banned?<p>This course does not permit AI. Your existing notes, cards and practice tools remain available.</p>:<>{policy?.stance!=='allowed'&&<label><input type="checkbox" checked={policyOk} onChange={e=>setPolicyOk(e.target.checked)}/> I checked the course policy and this study use is permitted.</label>}<label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Send the selected text and these study preferences to my configured AI service.</label></>}{!configured()&&<p>Guide generation requires an AI connection. <button onClick={()=>dispatch({type:'go',screen:'connect'})}>View connections</button></p>}<div className="portal-actions"><button className="portal-primary" disabled={!!busy||!formats.length||!chosen.length||!consent||banned||(!policyOk&&policy?.stance!=='allowed')||!configured()} onClick={()=>void generate()}>{busy==='all'?'Creating guide…':draft.value?'Create another guide':'Create study guide'}</button>{busy&&busy!=='reading'&&<button onClick={()=>abort.current?.abort()}>Cancel generation</button>}<span className="portal-muted">{configured()?`Uses ${routeLabel()}. Usage depends on the selected formats and text.`:'Existing study tools can still use your prepared course material.'}</span></div></div></section>
  {notice&&<p className="studio-notice" role="status">{notice}</p>}
  {draft.value&&<section className="portal-panel"><div className="portal-heading"><div><span className="portal-eyebrow">AI-assisted draft · Saved temporarily on this device</span><h3>Your study guide</h3><p>Matched quotations support source review; they do not guarantee an AI explanation is correct.</p></div><button className="portal-primary" disabled={!!busy} onClick={save}>Save & open in Write</button></div><p className="portal-muted">Write keeps the guide with your course and provides Word download, PDF printing and further editing.</p>{sections.length?sections.map(section=><article className="studio-section" key={section.id}><h4>{section.title}</h4>{section.diagram&&<Drawing language="mermaid" code={section.diagram}/>}<textarea disabled={!!busy} aria-label={`Edit ${section.title}`} value={section.body} rows={10} onChange={e=>commit(sections.map(s=>s.id===section.id?{...s,body:e.target.value}:s),usedSources)}/><details><summary>View cited material</summary>{section.citations.map((c,index)=>{const s=usedSources.find(source=>source.id===c.sourceId);const place=s&&c.at?quoteContext(s.text,c.at):null;return <blockquote key={`${c.sourceId}-${index}`}><strong>{s?.title} · {citationLocation(s,c.at)}</strong><p>{c.quote}</p>{s?.fileId&&<button onClick={()=>void openFile(s.fileId!)}>Open original file</button>}<details><summary>{place?'Read it where it sits in the source':'Read the source excerpt'}</summary>{place?<p className="study-cite-place">{place.before}<mark>{place.match}</mark>{place.after}</p>:<pre>{s?.text}</pre>}</details></blockquote>;})}</details><div className="portal-actions"><button disabled={!!busy||banned||!consent||!configured()||!canRegenerate||(!policyOk&&policy?.stance!=='allowed')} onClick={()=>void generate(section)}>Regenerate this section</button><button onClick={()=>speak(section.body)}>Read aloud</button><button onClick={()=>window.speechSynthesis?.cancel()}>Stop audio</button></div></article>):<label>Restored study draft<textarea disabled={!!busy} rows={18} value={draft.value} onChange={e=>draft.set(e.target.value)}/></label>}</section>}
 </div>;
}
