-- GENERATED by scripts/generate-seed.ts from lib/benchmark/benchmark.config.ts. Do not edit by hand.
-- Seeds the canonical 12-workflow template suite. Safe to run repeatedly.
-- Run as the database owner (supabase db reset does; in the SQL editor you are postgres).
-- Users get their own editable copy through the clone_benchmark_template() RPC.

insert into public.benchmark_suites (id, name, description, owner_id, organization_id, is_template)
values ('00000000-0000-4000-8000-0000000b3c01', 'Semester AI Workspace Benchmark — 12 Workflows',
  'Canonical benchmark: the same 12 workflow prompts run on Claude Artifacts, ChatGPT Canvas and v0.', null, null, true)
on conflict (id) do update set name = excluded.name, description = excluded.description;

insert into public.benchmark_tasks
  (suite_id, task_number, slug, title, category, prompt, requirements, capabilities,
   acceptance_criteria, recommended_platform, rubric_weights, requires_persistence)
values
  ('00000000-0000-4000-8000-0000000b3c01', 1, 'sortable-artifact-tracker', 'Sortable artifact tracker', 'React UI', 'Build a responsive client-side artifact tracker with 100 sample records, search, multi-select filters, sorting, status updates, a detail drawer, local state, CSV export, and accessible keyboard controls.',
   '["100 realistic sample records","Search, multi-select filters and sortable columns","Status updates reflected in the table","Detail drawer","CSV export","Keyboard-accessible controls"]'::jsonb,
   '{"react":true,"clientState":true,"csvExport":true}'::jsonb,
   '["Exactly 100 sample records load","Search narrows rows; multi-select filters combine correctly","Every sortable column toggles ascending/descending","Changing a status updates the row and any active filter","CSV download contains the currently filtered rows","All controls reachable and operable by keyboard; drawer traps and restores focus"]'::jsonb,
   'claude-artifacts', '{"correctness":25,"code_quality":20,"rendering":20,"state_management":20,"maintainability":10,"handoff":3,"sandbox_fit":2,"persistence":0}'::jsonb, false),
  ('00000000-0000-4000-8000-0000000b3c01', 2, 'interactive-onboarding-prototype', 'Interactive onboarding prototype', 'Product design', 'Build a clickable product onboarding prototype with an empty state, a multi-step setup flow, realistic sample data, validation feedback, completion state, and responsive layouts.',
   '["Empty state","Multi-step setup flow","Realistic sample data","Inline validation feedback","Completion state","Responsive layouts"]'::jsonb,
   '{"react":true,"clientState":true}'::jsonb,
   '["Empty state leads into step 1","Steps cannot be skipped while invalid; errors name the field","Back/next preserves entered values","Completion state summarizes the setup","Layout works at phone and desktop widths"]'::jsonb,
   'claude-artifacts', '{"correctness":20,"code_quality":15,"rendering":30,"state_management":20,"maintainability":5,"handoff":5,"sandbox_fit":5,"persistence":0}'::jsonb, false),
  ('00000000-0000-4000-8000-0000000b3c01', 3, 'b2b-saas-landing-page', 'B2B SaaS landing page', 'Marketing', 'Build a polished responsive B2B SaaS landing page with navigation, hero, product workflow, benefits, proof, testimonial placeholders, FAQ, pricing CTA, and accessible semantic HTML.',
   '["Navigation","Hero","Product workflow section","Benefits and proof","Testimonial placeholders","FAQ","Pricing CTA","Semantic, accessible HTML"]'::jsonb,
   '{"react":false}'::jsonb,
   '["All listed sections present, in a sensible narrative order","Uses landmark elements and a single h1; passes a contrast check","Responsive from 360px to 1440px with no horizontal scroll","FAQ is keyboard operable","Placeholders are clearly marked, not fabricated customer claims"]'::jsonb,
   'claude-artifacts', '{"correctness":20,"code_quality":15,"rendering":35,"state_management":5,"maintainability":10,"handoff":10,"sandbox_fit":5,"persistence":0}'::jsonb, false),
  ('00000000-0000-4000-8000-0000000b3c01', 4, 'multi-tenant-system-architecture-diagram', 'Multi-tenant system architecture diagram', 'Engineering', 'Create a Mermaid architecture diagram for a Next.js application using Supabase Auth, Postgres, Storage, Row Level Security, Stripe, webhooks, Vercel deployment, observability, and audit logs.',
   '["Valid Mermaid syntax","All named services present","Trust boundaries and data flow direction","Legend or notes"]'::jsonb,
   '{"mermaid":true,"documentation":true}'::jsonb,
   '["Diagram renders without syntax errors","Every service in the prompt appears exactly once","Client, server and database trust boundaries are distinguishable","Webhook ingress and audit-log writes are shown","Source is exportable as a .mmd file"]'::jsonb,
   'claude-artifacts', '{"correctness":30,"code_quality":5,"rendering":30,"state_management":5,"maintainability":10,"handoff":15,"sandbox_fit":5,"persistence":0}'::jsonb, false),
  ('00000000-0000-4000-8000-0000000b3c01', 5, 'technical-design-document', 'Technical design document', 'Engineering documentation', 'Write a technical design document for a multi-tenant artifact catalog. Include context, goals, non-goals, user flows, architecture, data model, RLS, API design, risks, failure modes, observability, rollout, testing, and open questions.',
   '["All fourteen named sections","Concrete data model","RLS described per table","Explicit risks and open questions"]'::jsonb,
   '{"documentation":true}'::jsonb,
   '["Every requested section present and non-trivial","Data model lists tables, keys and relationships","RLS section states who can read/write each table","Open questions are real unknowns, not filler","Exports cleanly to Markdown and DOCX/PDF"]'::jsonb,
   'chatgpt-canvas', '{"correctness":35,"code_quality":5,"rendering":10,"state_management":5,"maintainability":15,"handoff":25,"sandbox_fit":5,"persistence":0}'::jsonb, false),
  ('00000000-0000-4000-8000-0000000b3c01', 6, 'product-launch-presentation', 'Product launch presentation', 'GTM', 'Create a slide-by-slide product launch narrative for a B2B SaaS feature. Cover audience, problem, positioning, product walkthrough, proof, launch channels, sales enablement, timeline, metrics, risks, and speaker notes.',
   '["Slide-by-slide structure","All named topics covered","Speaker notes per slide","Metrics and timeline"]'::jsonb,
   '{"documentation":true}'::jsonb,
   '["Each slide has a title, key points and speaker notes","Narrative flows from problem to metrics to risks","Metrics are measurable and time-bound","No fabricated customer proof presented as fact","Exportable to Markdown or DOCX/PDF"]'::jsonb,
   'chatgpt-canvas', '{"correctness":25,"code_quality":5,"rendering":25,"state_management":5,"maintainability":10,"handoff":25,"sandbox_fit":5,"persistence":0}'::jsonb, false),
  ('00000000-0000-4000-8000-0000000b3c01', 7, 'subscription-csv-analysis', 'Subscription CSV analysis', 'Analytics', 'Write a Python script that reads subscription events from CSV, computes monthly active customers, gross logo churn, gross revenue churn, net revenue retention, creates a clean summary CSV, and produces a short Markdown report.',
   '["Reads subscription events CSV","Monthly active customers","Gross logo churn and gross revenue churn","Net revenue retention","Summary CSV and Markdown report"]'::jsonb,
   '{"python":true,"csvExport":true}'::jsonb,
   '["Script runs against a sample CSV without errors","Metric definitions are stated and calculated correctly on a hand-checked sample","Handles missing/duplicate rows with explicit behavior","Writes summary CSV and Markdown report files","No network access or secrets required"]'::jsonb,
   'chatgpt-canvas', '{"correctness":30,"code_quality":25,"rendering":5,"state_management":10,"maintainability":15,"handoff":10,"sandbox_fit":5,"persistence":0}'::jsonb, false),
  ('00000000-0000-4000-8000-0000000b3c01', 8, 'reusable-react-metric-dashboard', 'Reusable React metric dashboard', 'React UI', 'Build a reusable TypeScript React dashboard component with KPI cards, loading and empty states, filters, a data table, an accessible modal detail view, and realistic mock data. Do not use external UI libraries.',
   '["TypeScript","KPI cards","Loading and empty states","Filters and data table","Accessible modal","No external UI libraries"]'::jsonb,
   '{"react":true,"typescript":true,"clientState":true}'::jsonb,
   '["Compiles under strict TypeScript","Loading, empty and populated states are all reachable","Filters update KPIs and table consistently","Modal traps focus, closes on Escape and restores focus","No UI-library dependencies; props are typed and documented"]'::jsonb,
   'v0', '{"correctness":25,"code_quality":25,"rendering":20,"state_management":20,"maintainability":5,"handoff":3,"sandbox_fit":2,"persistence":0}'::jsonb, false),
  ('00000000-0000-4000-8000-0000000b3c01', 9, 'authenticated-nextjs-route-handler', 'Authenticated Next.js route handler', 'Next.js', 'Build a Next.js App Router route handler for creating artifact records. Require authentication, validate request data, enforce organization membership, return typed JSON errors, and document request/response examples.',
   '["Route handler","Authentication required","Request validation","Organization membership enforced","Typed JSON errors","Request/response examples"]'::jsonb,
   '{"nextjs":true,"serverCode":true,"auth":true,"database":true,"persistentState":true}'::jsonb,
   '["Unauthenticated requests return 401 with a typed error body","Invalid bodies return 400 with field-level errors","A non-member of the organization receives 403/404, never the record","Valid requests persist a row and return it","Examples match the real behavior"]'::jsonb,
   'v0', '{"correctness":25,"code_quality":20,"rendering":5,"state_management":10,"maintainability":10,"handoff":5,"sandbox_fit":10,"persistence":15}'::jsonb, true),
  ('00000000-0000-4000-8000-0000000b3c01', 10, 'supabase-artifact-crud-workflow', 'Supabase artifact CRUD workflow', 'Full stack', 'Build a Next.js App Router artifact catalog backed by Supabase Postgres. Include migration SQL, RLS, server actions, typed queries, create/edit/delete flows, filtering, validation, loading states, and error handling.',
   '["Migration SQL","RLS policies","Server actions","Typed queries","Create/edit/delete","Filtering, validation, loading and error states"]'::jsonb,
   '{"nextjs":true,"supabase":true,"database":true,"rls":true,"serverCode":true,"persistentState":true}'::jsonb,
   '["Migration applies cleanly to an empty database","RLS blocks another user''s rows (verified with two users)","Create, edit and delete persist across a reload","Invalid input is rejected server-side with messages","Loading and error states are visible in the UI"]'::jsonb,
   'v0', '{"correctness":25,"code_quality":15,"rendering":5,"state_management":15,"maintainability":10,"handoff":5,"sandbox_fit":5,"persistence":20}'::jsonb, true),
  ('00000000-0000-4000-8000-0000000b3c01', 11, 'cookie-based-supabase-auth', 'Cookie-based Supabase Auth', 'Authentication', 'Build Supabase Auth for Next.js App Router using separate browser/server clients, session refresh middleware, a magic-link sign-in page, protected routes, sign-out, and secure environment variable guidance.',
   '["Separate browser and server clients","Session refresh middleware/proxy","Magic-link sign-in page","Protected routes","Sign-out","Environment variable guidance"]'::jsonb,
   '{"nextjs":true,"supabase":true,"auth":true,"serverCode":true,"persistentState":true}'::jsonb,
   '["Uses @supabase/ssr with distinct browser and server clients","Session is refreshed on each request; server validates with getUser()","Magic link completes through a token-hash confirm route","Protected routes redirect when signed out; session survives reload","No service-role key is exposed to the browser"]'::jsonb,
   'v0', '{"correctness":30,"code_quality":15,"rendering":5,"state_management":15,"maintainability":10,"handoff":5,"sandbox_fit":5,"persistence":15}'::jsonb, true),
  ('00000000-0000-4000-8000-0000000b3c01', 12, 'multi-tenant-saas-workspace', 'Multi-tenant SaaS workspace', 'SaaS architecture', 'Build a multi-tenant Next.js workspace with organizations, memberships, owner/admin/member/viewer roles, Supabase Auth, Postgres tables, Row Level Security, server-side authorization, audit logs, and a responsive admin dashboard.',
   '["Organizations and memberships","Four roles","Supabase Auth","RLS on every table","Server-side authorization","Audit logs","Responsive admin dashboard"]'::jsonb,
   '{"nextjs":true,"supabase":true,"auth":true,"rls":true,"multiTenant":true,"serverCode":true,"database":true,"persistentState":true}'::jsonb,
   '["A member of org A cannot read or write org B''s rows","A viewer cannot write; only owner/admin manage members","The last owner cannot be removed","Security-relevant actions write audit-log rows","Dashboard is responsive and shows loading/empty/error states"]'::jsonb,
   'v0', '{"correctness":30,"code_quality":15,"rendering":5,"state_management":15,"maintainability":5,"handoff":5,"sandbox_fit":5,"persistence":20}'::jsonb, true)
on conflict (suite_id, task_number) do update set
  slug = excluded.slug, title = excluded.title, category = excluded.category, prompt = excluded.prompt,
  requirements = excluded.requirements, capabilities = excluded.capabilities,
  acceptance_criteria = excluded.acceptance_criteria, recommended_platform = excluded.recommended_platform,
  rubric_weights = excluded.rubric_weights, requires_persistence = excluded.requires_persistence;
