// Generated by pipeline/lessons.py — do not edit by hand.
// Re-render with: python3 pipeline/lessons.py econ
import type { Lesson } from '../../../lib/types';

const lessons: Record<number, Lesson> = {
  "0": {
    "unit": 0,
    "title": "How to actually pass this class",
    "file": "/audio/lessons/econ/unit-0.mp3",
    "seconds": 106,
    "len": "1:46",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "How to actually pass this class"
      },
      {
        "at": 5.19,
        "kind": "q",
        "text": "How is the grade built?"
      },
      {
        "at": 8.92,
        "kind": "a",
        "text": "80% exams, 20% problem sets, plus up to 3% extra credit from Top Hat. Your best exam counts 30%, the other two 25% each — or swap Midterm 3 for a comprehensive final worth 40% if it helps."
      },
      {
        "at": 24.56,
        "kind": "q",
        "text": "What quietly protects you in the syllabus?"
      },
      {
        "at": 29.22,
        "kind": "a",
        "text": "Your lowest problem set is dropped (missing ones can be emailed at term’s end for 50%), and about five classes of Top Hat are excused. But no pset extensions, ever."
      },
      {
        "at": 39.47,
        "kind": "q",
        "text": "Step 1 of the four-step method?"
      },
      {
        "at": 43.76,
        "kind": "a",
        "text": "Review each slide deck right after lecture, ruthlessly: could you explain every point to a friend, out loud, with no notes? He says 95% of students fool themselves here."
      },
      {
        "at": 54.1,
        "kind": "q",
        "text": "Step 2 and 3?"
      },
      {
        "at": 57.9,
        "kind": "a",
        "text": "Do the psets alone first — every problem targets one building block, so ask which concept it is testing. Then friend, then TA. Then read the answer key carefully, including for questions you got right: a right answer for the wrong reason still costs you."
      },
      {
        "at": 72.3,
        "kind": "q",
        "text": "Step 4, and the thing he asks you to do yourself?"
      },
      {
        "at": 77.62,
        "kind": "a",
        "text": "Practice exams, timed and closed-note — then modify every question. What would make a different answer correct? Can you reverse it Jeopardy-style? He asks you to do this rep yourself rather than having AI generate questions for you."
      },
      {
        "at": 89.66,
        "kind": "q",
        "text": "What separates A students?"
      },
      {
        "at": 93.68,
        "kind": "a",
        "text": "Memorizers do fine until a question asks them to do something new with a definition. Top grades go to students who learned the connections between building blocks, not just the blocks."
      },
      {
        "at": 103.74,
        "kind": "close",
        "text": "How to actually pass this class — 6 cards"
      }
    ]
  },
  "1": {
    "unit": 1,
    "title": "What economics is",
    "file": "/audio/lessons/econ/unit-1.mp3",
    "seconds": 69,
    "len": "1:10",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "What economics is"
      },
      {
        "at": 4.4,
        "kind": "q",
        "text": "Define economics and an economic agent."
      },
      {
        "at": 9.82,
        "kind": "a",
        "text": "The study of how agents choose to allocate scarce resources and how those choices affect society. An agent is anyone making choices — a person, household, firm or government."
      },
      {
        "at": 20.46,
        "kind": "q",
        "text": "Positive vs. normative — and the trap?"
      },
      {
        "at": 25.37,
        "kind": "a",
        "text": "Positive is an objective, falsifiable claim; normative is a value judgment. The trap: a positive statement can be wrong and still be positive. What makes it positive is that it could be checked."
      },
      {
        "at": 36.55,
        "kind": "q",
        "text": "State the course definition of equilibrium — both halves."
      },
      {
        "at": 42.28,
        "kind": "a",
        "text": "Everyone is optimizing AND nobody believes they would personally be better off changing their own choice, holding everyone else’s fixed. Students drop the second half."
      },
      {
        "at": 50.61,
        "kind": "q",
        "text": "The two approaches to cause and effect in economics?"
      },
      {
        "at": 55.83,
        "kind": "a",
        "text": "Theory-driven — build a model, change one thing, see what happens. Statistics-driven — imitate a controlled experiment using observational data. Real research sits on the spectrum between."
      },
      {
        "at": 67.04,
        "kind": "close",
        "text": "What economics is — 4 cards"
      }
    ]
  },
  "2": {
    "unit": 2,
    "title": "Optimization & opportunity cost",
    "file": "/audio/lessons/econ/unit-2.mp3",
    "seconds": 56,
    "len": "0:57",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "Optimization & opportunity cost"
      },
      {
        "at": 5.26,
        "kind": "q",
        "text": "Define opportunity cost."
      },
      {
        "at": 9.28,
        "kind": "a",
        "text": "The value of the best foregone alternative — used both as a broad idea and to put a dollar value on time."
      },
      {
        "at": 15.36,
        "kind": "q",
        "text": "Why do sunk costs never matter?"
      },
      {
        "at": 19.86,
        "kind": "a",
        "text": "They are already spent and unrecoverable. Only future costs and benefits bear on what to do next."
      },
      {
        "at": 25.78,
        "kind": "q",
        "text": "Total vs. marginal analysis — why does marginal win?"
      },
      {
        "at": 31.51,
        "kind": "a",
        "text": "Same answer, less arithmetic. Keep going while MB ≥ MC and stop where they cross, instead of computing net benefit for every option."
      },
      {
        "at": 40.48,
        "kind": "q",
        "text": "Where is the optimum, exactly?"
      },
      {
        "at": 44.65,
        "kind": "a",
        "text": "Where MB and MC cross — not where total benefit is highest and not where cost is lowest. MB falls as you do more; MC usually rises."
      },
      {
        "at": 53.92,
        "kind": "close",
        "text": "Optimization & opportunity cost — 4 cards"
      }
    ]
  },
  "3": {
    "unit": 3,
    "title": "Supply, demand, equilibrium",
    "file": "/audio/lessons/econ/unit-3.mp3",
    "seconds": 79,
    "len": "1:20",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "Supply, demand, equilibrium"
      },
      {
        "at": 5.47,
        "kind": "q",
        "text": "What do the heights of the two curves mean?"
      },
      {
        "at": 9.82,
        "kind": "a",
        "text": "Demand height is willingness to pay — the buyer’s marginal benefit. Supply height is willingness to accept — the seller’s marginal cost."
      },
      {
        "at": 17.66,
        "kind": "q",
        "text": "Movement along vs. shift — the #1 tested thing?"
      },
      {
        "at": 23.42,
        "kind": "a",
        "text": "A change in the good’s own price moves you along the curve. A change in anything else shifts the whole curve. If price changed on its own, do not shift."
      },
      {
        "at": 31.78,
        "kind": "q",
        "text": "What shifts demand? What shifts supply?"
      },
      {
        "at": 36.46,
        "kind": "a",
        "text": "Demand: income, substitute and complement prices, tastes, expectations, number of buyers. Supply: input prices, technology, expectations, number of sellers."
      },
      {
        "at": 48.2,
        "kind": "q",
        "text": "Both curves shift — what can you conclude?"
      },
      {
        "at": 52.86,
        "kind": "a",
        "text": "Whichever effect the two shifts push in the same direction is certain; the other is ambiguous and depends on which shift is bigger."
      },
      {
        "at": 60.05,
        "kind": "q",
        "text": "Ceiling or floor — which gives a shortage?"
      },
      {
        "at": 65.1,
        "kind": "a",
        "text": "An effective ceiling sits below equilibrium → excess demand → shortage, with trade only up to Qs. A floor sits above → excess supply. A ceiling above equilibrium is not binding and does nothing."
      },
      {
        "at": 76.89,
        "kind": "close",
        "text": "Supply, demand, equilibrium — 5 cards"
      }
    ]
  },
  "4": {
    "unit": 4,
    "title": "Surplus & elasticity",
    "file": "/audio/lessons/econ/unit-4.mp3",
    "seconds": 126,
    "len": "2:06",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "Surplus & elasticity"
      },
      {
        "at": 4.67,
        "kind": "q",
        "text": "Write the midpoint elasticity formula."
      },
      {
        "at": 9.39,
        "kind": "a",
        "text": "ε = [(Q₂−Q₁) ÷ ((Q₁+Q₂)/2)] ÷ [(P₂−P₁) ÷ ((P₁+P₂)/2)]. The only elasticity formula you need."
      },
      {
        "at": 18.95,
        "kind": "q",
        "text": "Price $4→$6, quantity 100→80. Elastic or inelastic?"
      },
      {
        "at": 26.46,
        "kind": "a",
        "text": "%ΔQ = −20/90 = −22.2%; %ΔP = 2/5 = 40%; ε = −0.56 → inelastic."
      },
      {
        "at": 39.83,
        "kind": "q",
        "text": "Which way does revenue move?"
      },
      {
        "at": 44.06,
        "kind": "a",
        "text": "Inelastic: revenue moves with price. Elastic: revenue moves against it. Unit elastic: revenue unchanged and at its maximum."
      },
      {
        "at": 52.27,
        "kind": "q",
        "text": "Why is elasticity not slope?"
      },
      {
        "at": 56.49,
        "kind": "a",
        "text": "A straight-line demand curve has one constant slope and a changing elasticity — elastic on the upper half, unit elastic at the midpoint, inelastic on the lower half. Revenue peaks at that midpoint."
      },
      {
        "at": 67.64,
        "kind": "q",
        "text": "What makes demand more elastic?"
      },
      {
        "at": 71.98,
        "kind": "a",
        "text": "More close substitutes, a luxury rather than a necessity, a large share of the budget, a long time to adjust, and a narrowly defined market."
      },
      {
        "at": 80.95,
        "kind": "q",
        "text": "Consumer surplus — the two ways to find it?"
      },
      {
        "at": 85.59,
        "kind": "a",
        "text": "From a table, subtract price from each unit’s WTP and add the positives. From a graph, the area below demand and above price out to Q traded — usually ½ × base × height."
      },
      {
        "at": 96.91,
        "kind": "q",
        "text": "Cross-price and income elasticity — what does the sign say?"
      },
      {
        "at": 102.83,
        "kind": "a",
        "text": "Cross-price positive = substitutes, negative = complements. Income positive = normal good, negative = inferior good."
      },
      {
        "at": 111.69,
        "kind": "q",
        "text": "“Bang for your buck” condition?"
      },
      {
        "at": 115.57,
        "kind": "a",
        "text": "You are optimizing when MBx/Px = MBy/Py. If one side is bigger, buy more of that good."
      },
      {
        "at": 123.48,
        "kind": "close",
        "text": "Surplus & elasticity — 8 cards"
      }
    ]
  },
  "5": {
    "unit": 5,
    "title": "Producers & cost curves",
    "file": "/audio/lessons/econ/unit-5.mp3",
    "seconds": 106,
    "len": "1:47",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "Producers & cost curves"
      },
      {
        "at": 4.93,
        "kind": "q",
        "text": "Why does MC eventually rise?"
      },
      {
        "at": 9.44,
        "kind": "a",
        "text": "The law of diminishing returns — adding more of one input to fixed inputs eventually raises output by smaller and smaller amounts. Ten cooks, one oven."
      },
      {
        "at": 18.99,
        "kind": "q",
        "text": "Economic vs. accounting profit?"
      },
      {
        "at": 23.36,
        "kind": "a",
        "text": "Economic profit subtracts all opportunity costs including the salary you gave up; accounting profit subtracts only explicit money costs. Economic ≤ accounting, always."
      },
      {
        "at": 34.44,
        "kind": "q",
        "text": "Why does MC cut AVC and ATC at their minimums?"
      },
      {
        "at": 40.19,
        "kind": "a",
        "text": "An average falls while the next value is below it and rises once the next value is above it — so the curves cross exactly at the bottom."
      },
      {
        "at": 48.46,
        "kind": "q",
        "text": "Shutdown vs. exit rule?"
      },
      {
        "at": 52.7,
        "kind": "a",
        "text": "Short run: shut down if P < min AVC. Long run: exit if P < min ATC. Breakeven price = min ATC, where economic profit is exactly zero."
      },
      {
        "at": 62.9,
        "kind": "q",
        "text": "The trap on computing marginals from a table?"
      },
      {
        "at": 67.78,
        "kind": "a",
        "text": "Divide by the change in Q. If output jumps 10 → 14, MC = ΔTC ÷ 4, not ΔTC."
      },
      {
        "at": 75.81,
        "kind": "q",
        "text": "What is the firm’s supply curve?"
      },
      {
        "at": 79.89,
        "kind": "a",
        "text": "Its MC curve above the relevant shutdown point. Add firms horizontally for market supply; entry drives price to min long-run ATC and zero economic profit."
      },
      {
        "at": 89.46,
        "kind": "q",
        "text": "What makes supply more elastic?"
      },
      {
        "at": 93.54,
        "kind": "a",
        "text": "Anything that makes the producer more flexible — inventories, non-perishability, the long run, easily adjusted variable inputs. Heavy fixed inputs make it less elastic."
      },
      {
        "at": 104.02,
        "kind": "close",
        "text": "Producers & cost curves — 7 cards"
      }
    ]
  },
  "6": {
    "unit": 6,
    "title": "The invisible hand & efficiency",
    "file": "/audio/lessons/econ/unit-6.mp3",
    "seconds": 63,
    "len": "1:04",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "The invisible hand & efficiency"
      },
      {
        "at": 5.01,
        "kind": "q",
        "text": "What does “efficient” mean here?"
      },
      {
        "at": 8.84,
        "kind": "a",
        "text": "Total surplus (CS + PS) is maximised. Every unit left of Q* has MB above MC and is worth trading; every unit right of it costs more than it is worth."
      },
      {
        "at": 19.13,
        "kind": "q",
        "text": "Define deadweight loss and how to compute it."
      },
      {
        "at": 24.0,
        "kind": "a",
        "text": "The surplus destroyed when the market does not trade the efficient quantity. On a graph, the triangle between D and S over the units that failed to trade: ½ × base × height."
      },
      {
        "at": 34.44,
        "kind": "q",
        "text": "Pareto efficient vs. Pareto improvement?"
      },
      {
        "at": 39.44,
        "kind": "a",
        "text": "Pareto efficient: you cannot make anyone better off without making someone worse off. A Pareto improvement makes at least one person better off and nobody worse off."
      },
      {
        "at": 48.84,
        "kind": "q",
        "text": "The equity–efficiency tradeoff?"
      },
      {
        "at": 52.94,
        "kind": "a",
        "text": "Efficiency is the size of total surplus; equity is who gets it. Economics alone cannot say which balance is right — that is normative."
      },
      {
        "at": 60.97,
        "kind": "close",
        "text": "The invisible hand & efficiency — 4 cards"
      }
    ]
  },
  "7": {
    "unit": 7,
    "title": "Externalities",
    "file": "/audio/lessons/econ/unit-7.mp3",
    "seconds": 81,
    "len": "1:22",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "Externalities"
      },
      {
        "at": 4.11,
        "kind": "q",
        "text": "Name the four curves and what each captures."
      },
      {
        "at": 9.01,
        "kind": "a",
        "text": "MPB = value to the buyer (the demand curve). MSB = MPB plus spillover benefits. MPC = cost to the seller (the supply curve). MSC = MPC plus spillover costs."
      },
      {
        "at": 21.6,
        "kind": "q",
        "text": "Negative externality — which way does the market err?"
      },
      {
        "at": 26.94,
        "kind": "a",
        "text": "Overproduction. MSC sits above MPC, so Q_market exceeds Q_optimal and the gap is deadweight loss. Flip it for a positive externality: MSB above MPB, underproduction."
      },
      {
        "at": 38.79,
        "kind": "q",
        "text": "State the Coase theorem — and its limit."
      },
      {
        "at": 43.29,
        "kind": "a",
        "text": "With clear property rights and low transaction costs, the parties bargain to the efficient quantity no matter who holds the right. Who holds it changes who pays whom, not the efficient quantity. It fails with many parties, murky rights or costly bargaining — which is why it does not solve climate change."
      },
      {
        "at": 59.41,
        "kind": "q",
        "text": "Command-and-control vs. market-based fixes?"
      },
      {
        "at": 64.49,
        "kind": "a",
        "text": "Command-and-control sets direct rules — caps, bans, mandated technology. Market-based tools — taxes, subsidies, tradable permits — change prices so private incentives line up with social ones and let firms choose how to respond."
      },
      {
        "at": 78.99,
        "kind": "close",
        "text": "Externalities — 4 cards"
      }
    ]
  },
  "8": {
    "unit": 8,
    "title": "Monopoly",
    "file": "/audio/lessons/econ/unit-8.mp3",
    "seconds": 71,
    "len": "1:11",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "Monopoly"
      },
      {
        "at": 4.1,
        "kind": "q",
        "text": "Why does MR lie below demand for a monopolist?"
      },
      {
        "at": 9.38,
        "kind": "a",
        "text": "To sell one more unit it must cut price on every unit, so MR = the new unit’s price minus revenue lost on all previous ones. For a straight-line demand curve, MR has the same intercept and twice the slope."
      },
      {
        "at": 22.2,
        "kind": "q",
        "text": "The two-step move for monopoly price?"
      },
      {
        "at": 26.51,
        "kind": "a",
        "text": "Find Q where MR = MC, then go straight up to the demand curve to read the price. Setting price at the MR = MC intersection is the classic mistake."
      },
      {
        "at": 36.05,
        "kind": "q",
        "text": "What are the two kinds of barrier to entry?"
      },
      {
        "at": 40.58,
        "kind": "a",
        "text": "Legal — patents, licences, government franchises. Natural — huge economies of scale, control of a key resource, network effects."
      },
      {
        "at": 49.79,
        "kind": "q",
        "text": "Perfect price discrimination — the striking result?"
      },
      {
        "at": 55.07,
        "kind": "a",
        "text": "The firm produces the efficient quantity, so DWL = 0 — but CS = 0 and the firm captures the entire surplus. Efficient and not equitable: the cleanest proof that efficiency ≠ fairness."
      },
      {
        "at": 68.63,
        "kind": "close",
        "text": "Monopoly — 4 cards"
      }
    ]
  },
  "9": {
    "unit": 9,
    "title": "Game theory",
    "file": "/audio/lessons/econ/unit-9.mp3",
    "seconds": 64,
    "len": "1:04",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "Game theory"
      },
      {
        "at": 4.07,
        "kind": "q",
        "text": "Nash equilibrium vs. dominant strategy?"
      },
      {
        "at": 9.22,
        "kind": "a",
        "text": "Nash: both players are playing a best response, so neither would unilaterally switch. Dominant: your best response no matter what the other does."
      },
      {
        "at": 17.52,
        "kind": "q",
        "text": "How do you solve a payoff matrix?"
      },
      {
        "at": 21.8,
        "kind": "a",
        "text": "For each of P2’s columns mark P1’s best payoff; for each of P1’s rows mark P2’s best. Any cell marked twice is a Nash equilibrium."
      },
      {
        "at": 30.78,
        "kind": "q",
        "text": "Prisoner’s dilemma — what is the point?"
      },
      {
        "at": 35.12,
        "kind": "a",
        "text": "(Fink, Fink) is the unique Nash equilibrium at 1,1 even though (Quiet, Quiet) pays 2,2. The gap between individual rationality and the group outcome is the whole dilemma."
      },
      {
        "at": 45.66,
        "kind": "q",
        "text": "How do you solve a game tree?"
      },
      {
        "at": 49.62,
        "kind": "a",
        "text": "Backward induction — start at the end, work out the last player’s move at each node, cross off branches they would never take, and work backwards. That is how you see that B’s threat to fight is not credible."
      },
      {
        "at": 61.4,
        "kind": "close",
        "text": "Game theory — 4 cards"
      }
    ]
  },
  "10": {
    "unit": 10,
    "title": "Competition & information",
    "file": "/audio/lessons/econ/unit-10.mp3",
    "seconds": 79,
    "len": "1:20",
    "cues": [
      {
        "at": 0.0,
        "kind": "title",
        "text": "Competition & information"
      },
      {
        "at": 4.97,
        "kind": "q",
        "text": "Why are cartels unstable?"
      },
      {
        "at": 9.07,
        "kind": "a",
        "text": "Collusion is a prisoner’s dilemma — each firm’s private incentive is to cheat and undercut."
      },
      {
        "at": 14.91,
        "kind": "q",
        "text": "What is HHI and why use it over a firm count?"
      },
      {
        "at": 20.45,
        "kind": "a",
        "text": "The sum of each firm’s squared percentage market share — four firms at 25% gives 2,500, a pure monopoly 10,000. It captures share; twenty firms where one holds 95% is not competitive."
      },
      {
        "at": 34.01,
        "kind": "q",
        "text": "Adverse selection vs. moral hazard?"
      },
      {
        "at": 38.95,
        "kind": "a",
        "text": "Adverse selection hides a type, before the deal — only sick people buy the insurance. Moral hazard hides an action, after it — insured drivers drive recklessly."
      },
      {
        "at": 48.45,
        "kind": "q",
        "text": "Explain the death spiral."
      },
      {
        "at": 52.43,
        "kind": "a",
        "text": "Insurers raise premiums to cover a sick pool, the healthiest drop out, the pool gets sicker, premiums rise again — adverse selection eating itself until the market can collapse."
      },
      {
        "at": 63.55,
        "kind": "q",
        "text": "Does every principal–agent relationship have moral hazard?"
      },
      {
        "at": 68.95,
        "kind": "a",
        "text": "No. Only when the principal cannot observe what the agent actually does — exactly the kind of distinction he writes a multiple-choice question around."
      },
      {
        "at": 77.06,
        "kind": "close",
        "text": "Competition & information — 5 cards"
      }
    ]
  }
};

export default lessons;
