/**
 * The single source of truth: which document is the current authoritative
 * version of each thing the company runs on, who owns it, when it was last
 * reviewed, and what it rests on.
 *
 * ## Why this is data
 *
 * The repository holds several hundred Markdown files. Many are audits of a
 * moment, several are plans that were overtaken, and a few are the thing
 * itself. A reader cannot tell which is which from the titles, and the danger
 * the closing brief names — "competing documents and inconsistent promises" —
 * is exactly what happens when two of them disagree and nobody has said which
 * one wins. So this module says, for each category, *one* path or `null`, and
 * `operatingsystem.test.ts` refuses a path that does not exist, a superseded
 * document with no redirect, a decision that is not in the log, and a
 * category that claims a document while calling itself missing.
 *
 * ## What "owner" means here
 *
 * A council seat from `launchreadiness.ts`, never a person. The seats are the
 * accountabilities the launch command defined; a document is owned by whoever
 * holds the seat, and the rendered page says which seats are held. Today none
 * is, and the page says that too, rather than printing a name nobody accepted.
 *
 * ## Version and review
 *
 * `version` counts reviews of the *entry* — the decision that this path is the
 * authoritative one and that its content was read and stands. It is not the
 * document's own revision count; git holds that. `nextReview` is a date, and
 * the test holds it after `lastReviewed`. Registers that change with every
 * merge are reviewed monthly; the rest quarterly.
 */

import type { Seat } from '../launchreadiness';

export type SourceStatus = 'current' | 'draft' | 'missing';

export interface Source {
  /** A slug, stable across renames of the category title. */
  id: string;
  /** The category as the closing brief names it. */
  category: string;
  /** The one authoritative path, repository-relative — or `null` when none exists. */
  path: string | null;
  /** `current`: read and stands. `draft`: the authoritative one, but not yet fit to act on. `missing`: nothing is. */
  status: SourceStatus;
  owner: Seat;
  version: number;
  lastReviewed: string;
  nextReview: string;
  /**
   * Documents this one replaced. A path may appear here only if that file
   * carries a redirect to the authoritative one (D-002 asks for exactly that
   * before a plan is retired), and the test reads the file to check.
   */
  supersedes: readonly string[];
  /** `D-nnn` from docs/DECISION-LOG.md, `ADR-nnnn` from docs/architecture/, or `DECISIONS §n` from DECISIONS.md. */
  decisions: readonly string[];
  /** Not authoritative, but read next. Every path must exist. */
  alsoRead?: readonly string[];
  /** What the authoritative document is, and is not. */
  note?: string;
  /** Required when `missing`: what would close it. */
  gap?: string;
}

/** The nineteen categories the closing brief lists, in its order. */
export const BRIEF_CATEGORIES: readonly string[] = [
  'Company strategy',
  'Product vision',
  'Master readiness register',
  'Role launch register',
  'Claims register',
  'Architecture decision records',
  'Roadmap',
  'Risk register',
  'Design system',
  'Accessibility register',
  'Security/compliance evidence index',
  'Integration catalog',
  'Data inventory and lineage',
  'Customer implementation method',
  'Support/runbook library',
  'Commercial catalog',
  'Contract templates',
  'Company site map',
  'Operations Console map',
];

const REVIEWED = '2026-09-28';
const MONTHLY = '2026-10-28';
const QUARTERLY = '2026-12-28';

export const SOURCES: readonly Source[] = [
  {
    id: 'strategy',
    category: 'Company strategy',
    path: 'docs/strategy/README.md',
    status: 'draft',
    owner: 'founder',
    version: 1,
    lastReviewed: '2026-10-04',
    nextReview: '2027-01-15',
    supersedes: [],
    decisions: ['DECISIONS §1', 'D-007', 'D-1151'],
    alsoRead: [
      'docs/strategy/THREE-YEAR-STRATEGY.md',
      'docs/strategy/BOARD-MEMO.md',
      'docs/strategy/SCORECARD.md',
      'MARKET-POSITION.md',
      'docs/operating-model/DEFENSIBILITY.md',
      'docs/gtm/EXECUTION-PLAN.md',
    ],
    note: 'A proposal until the founder approves FD-2026-001 in docs/strategy/FOUNDER-DECISION-LOG.md: no target in it is set, no decision in it is made, and it publishes no claim. It is the one-page strategy memo that docs/operating-model/OPERATING-RHYTHM.md schedules quarterly.',
  },
  {
    id: 'vision',
    category: 'Product vision',
    path: 'README.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-003', 'D-006'],
    alsoRead: ['SEMESTER-MASTER-COMMAND.md', 'docs/launch/WHAT-IS-SEMESTER.md'],
    note: 'The opening paragraph is the vision as it is sold today. SEMESTER-MASTER-COMMAND.md is the specification behind it, and says which of its sections were never supplied.',
  },
  {
    id: 'master-register',
    category: 'Master readiness register',
    path: 'docs/MASTER-LAUNCH-READINESS-REGISTER.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/LAUNCH-READINESS-COUNCIL.md', 'docs/GO-NO-GO-CHECKLIST.md'],
    note: 'Rendered from app/src/lib/masterregister.ts; a test holds every row to the kind of file it cites. Nothing is above `tested` until docs/evidence/ exists.',
  },
  {
    id: 'role-register',
    category: 'Role launch register',
    path: 'docs/ROLE-LAUNCH-REGISTER.md',
    status: 'current',
    owner: 'security',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: [],
    note: 'Rendered from app/src/lib/rolelaunch.ts, which reads the roles out of the migrations. All 63 roles are `modeled`; none is provisionable.',
  },
  {
    id: 'claims',
    category: 'Claims register',
    path: 'ops/claims/README.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-110'],
    alsoRead: ['app/src/lib/rollout-capabilities.ts', 'docs/launch/CONTENT-READINESS-REGISTER.md', 'ops/customer-commitments/README.md'],
    note: 'Rendered from app/src/lib/ops/claims.ts: every capability the public site asserts, the word it may carry, the master-register rows and tests behind it, and the pages it appears on. claims.test.ts reads the rendered site and refuses a word above its rows or a label the register does not know. It covers the public site; sales decks and RFP answers are not yet mapped (PRG-002). The capability inventory covers product promises, and ops/customer-commitments/ promises to a named customer.',
  },
  {
    id: 'adr',
    category: 'Architecture decision records',
    path: 'docs/architecture/README.md',
    status: 'current',
    owner: 'engineering',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['ADR-0001', 'ADR-0002', 'ADR-0003', 'ADR-0004', 'ADR-0005', 'ADR-0006'],
    note: 'Six records. Product decisions are not here: settled ones are in DECISIONS.md and the programme log is docs/DECISION-LOG.md.',
  },
  {
    id: 'roadmap',
    category: 'Roadmap',
    path: 'docs/PRODUCT-ROADMAP.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-002'],
    alsoRead: ['docs/90-DAY-LAUNCH-PROGRAM.md', 'docs/LMS-LEARNING-ROADMAP.md'],
    note: 'The unified-platform plan of record. The root-level plans it overtook (IMPLEMENTATION-PLAN.md, COMPLETION-PLAN.md, ACTION-PLAN.md) are not listed as superseded because none carries a redirect yet; D-002 makes that backlog item BL-0.3.',
  },
  {
    id: 'risk',
    category: 'Risk register',
    path: 'docs/operating-model/RISK-GOVERNANCE.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/LAUNCH-READINESS-COUNCIL.md', 'docs/trust/SOC2-READINESS.md', 'docs/EDGE-CASE-CATALOG.md'],
    note: 'Rendered from app/src/lib/governance/risk.ts: seventeen risks with likelihood, impact, tolerance, controls that must exist, residual and an owner seat; the appetite tiers; the exception rules reviewException() enforces (no indefinite exception, 90 days at most, P0 needs executive, security and legal); sixteen game days, none held. Owners are seats, not people, and no exception has been approved.',
  },
  {
    id: 'design',
    category: 'Design system',
    path: 'docs/design/SEMESTER-UI-CONSTITUTION.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/design/README.md', 'docs/DO-NOT-BUILD.md'],
    note: 'The quality contract the pull-request template cites (§9). Tokens live in app/src/styles/, primitives in app/src/components/ui.tsx, and the style and label audits run in `npm run lint`.',
  },
  {
    id: 'a11y',
    category: 'Accessibility register',
    path: 'docs/WCAG-UI-AUDIT-SCORECARD.md',
    status: 'current',
    owner: 'accessibility',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/market-readiness/ACCESSIBILITY_READINESS.md', 'docs/operating-model/ACCESSIBILITY-GOVERNANCE.md'],
    note: 'A per-component WCAG 2.2 scorecard where every score cites its test. It is not yet a findings register with remediation dates; the VPAT/ACR (master register A11Y-007) is on the proof calendar.',
  },
  {
    id: 'evidence',
    category: 'Security/compliance evidence index',
    path: 'docs/trust/EVIDENCE-REGISTER.md',
    status: 'current',
    owner: 'security',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-115'],
    alsoRead: ['docs/trust/COMPLIANCE-CROSSWALK.md', 'docs/PROOF-CALENDAR.md', 'docs/trust/README.md', 'docs/market-readiness/HECVAT_READINESS.md'],
    note: 'Rendered from app/src/lib/trust/evidence-register.ts: for every control a reviewer asks about, the artifact that would prove it operates, its owner seat, frequency, visibility and what the tree holds today. The index exists; no evidence has been produced. docs/evidence/ still does not exist, the master register still lets no row above `tested`, and the register refuses the word `produced` until it does. docs/PROOF-CALENDAR.md schedules the first artifacts; docs/EVIDENCE-REGISTER.md below is the dated artifacts the tree already holds and when each runs out.',
  },
  {
    id: 'integrations',
    category: 'Integration catalog',
    path: 'app/src/lib/integration/catalog.ts',
    status: 'current',
    owner: 'data',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-007', 'ADR-0003'],
    alsoRead: ['docs/UNIVERSITY_CONNECTIONS.md', 'docs/INTEGRATION-OPERATOR-RUNBOOK.md'],
    note: 'Written as data: provider domains, canonical entities, freshness and sync classes, and what no connector ingests by default; catalog.test.ts holds it to the SQL constraints. docs/UNIVERSITY_CONNECTIONS.md is the human record of what is actually connected.',
  },
  {
    id: 'data',
    category: 'Data inventory and lineage',
    path: 'RETENTION.md',
    status: 'current',
    owner: 'privacy',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['ADR-0001', 'ADR-0002'],
    alsoRead: ['docs/data-contract.md', 'docs/operating-model/DATA-STEWARDSHIP.md', 'docs/SUBPROCESSORS.md'],
    note: 'The inventory: every store and the clock that runs on it. Lineage — which client holds which field of the contract — is docs/data-contract.md, and who decides what a field means is DATA-STEWARDSHIP.md.',
  },
  {
    id: 'implementation',
    category: 'Customer implementation method',
    path: 'docs/operating-model/PILOT-TO-PRODUCTION.md',
    status: 'current',
    owner: 'success',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['DECISIONS §1'],
    alsoRead: ['docs/market-readiness/PILOT_PLAYBOOK.md', 'docs/90-DAY-LAUNCH-PROGRAM.md'],
    note: 'The lifecycle from directory listing to production tenant, held by app/src/lib/governance/rollout.ts. PILOT_PLAYBOOK.md is how a pilot is run once signed.',
  },
  {
    id: 'runbooks',
    category: 'Support/runbook library',
    path: 'docs/RUNBOOKS.md',
    status: 'current',
    owner: 'engineering',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/market-readiness/SUPPORT_PLAYBOOK.md'],
    note: 'An index, written for this register: the runbooks were real and scattered. app/src/lib/runbooklinks.test.ts holds every link in the operational set to a file that exists.',
  },
  {
    id: 'commercial',
    category: 'Commercial catalog',
    path: 'docs/operating-model/COMMERCIAL-GOVERNANCE.md',
    status: 'draft',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-009'],
    alsoRead: ['app/src/lib/plans.ts', 'docs/LAUNCH-DECISIONS.md'],
    note: 'Pricing governance and the deal desk, not a price list. The four packages are named in docs/LAUNCH-DECISIONS.md step 3 and the student plans in app/src/lib/plans.ts; no institutional price exists, and D-009 keeps billing out of the app for now.',
  },
  {
    id: 'contracts',
    category: 'Contract templates',
    path: 'docs/trust/PILOT-AGREEMENT-OUTLINE.md',
    status: 'draft',
    owner: 'privacy',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/trust/DPA-CHECKLIST.md', 'docs/legal/TERMS-OF-SERVICE-DRAFT.md', 'docs/legal/PRIVACY-POLICY-DRAFT.md'],
    note: 'Outlines for counsel, not agreement language: nothing in the repository may be signed. docs/LAUNCH-DECISIONS.md items 4 and 5 say what has to happen first.',
  },
  {
    id: 'site',
    category: 'Company site map',
    path: 'docs/PUBLIC-SITE.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-011', 'D-031'],
    note: 'The routes are `ROUTES` in app/src/site/render.tsx: 21 content pages and 4 tools, prerendered to static HTML. Every capability a page names is printed from the claims register with its status word.',
  },
  {
    id: 'console',
    category: 'Operations Console map',
    path: 'docs/OPERATIONS-CONSOLE-MAP.md',
    status: 'current',
    owner: 'engineering',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-110'],
    alsoRead: ['ops/operations-console/README.md', 'docs/CURRENT-SEMESTER-ARTIFACT-INVENTORY.md', 'docs/INTEGRATION-OPERATOR-RUNBOOK.md'],
    note: 'Rendered from VIEWS and CONTEXT_BAR in app/src/lib/ops/console.ts by console.test.ts: the console screen (app/src/screens/Console.tsx, behind console:operate), the context bar every view shows, its seven views, and the migration, check suite, screen and test that hold the capability behind each. The integration operator runbook still names functions and tables; the map names the screen that reads them.',
  },
  // ── "anything else": what the repository runs on that the brief's list did not name ──
  {
    id: 'decisions',
    category: 'Decision log',
    path: 'docs/DECISION-LOG.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-001', 'D-002'],
    alsoRead: ['DECISIONS.md'],
    note: 'The programme log, numbered D-nnn; DECISIONS.md holds the two long-lived product decisions. Every `decisions` entry on this page resolves to one of them or to an ADR.',
  },
  {
    id: 'do-not-build',
    category: 'Do-not-build register',
    path: 'docs/DO-NOT-BUILD.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['ops/strategic-boundaries/README.md'],
    note: 'Product-level anti-patterns, with the test that holds each. The company-level lines are ops/strategic-boundaries/.',
  },
  {
    id: 'boundaries',
    category: 'Strategic boundaries',
    path: 'ops/strategic-boundaries/README.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-029', 'D-034', 'D-045'],
    note: 'The twelve things Semester will not build, whoever asks, and what holds each.',
  },
  {
    id: 'commitments',
    category: 'Customer commitment register',
    path: 'ops/customer-commitments/README.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: [],
    note: 'Every promise made to a named customer, with its product dependency and its evidence. Empty until a customer exists, and the test says why.',
  },
  {
    id: 'console-controls',
    category: 'Operations console controls',
    path: 'ops/operations-console/README.md',
    status: 'current',
    owner: 'engineering',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-110'],
    alsoRead: ['docs/operating-model/CHANGE-MANAGEMENT.md', 'docs/LAUNCH-WAR-ROOM.md'],
    note: 'The policy the console reads, written before it existed: segregation of duties, data classification, the context bar and access basis, evidence-freshness escalation, the production rules a browser prototype could not hold (each now held by a check or a test), the five conversion steps at what exists today, and the thirteen capabilities the prototype faked with the file that replaced each. The Operations Console map above is rendered from the same file.',
  },
  {
    id: 'evidence-register',
    category: 'Evidence register',
    path: 'docs/EVIDENCE-REGISTER.md',
    status: 'current',
    owner: 'security',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-110'],
    alsoRead: ['docs/PROOF-CALENDAR.md', 'ops/claims/README.md'],
    note: 'Rendered from app/src/lib/ops/evidence.ts: every dated artifact the tree holds today, the date its file states, how long it is good for, and the claims and register rows resting on it. Not the evidence index above (docs/trust/EVIDENCE-REGISTER.md), which names the artifact each control would need and holds every row below `produced` until docs/evidence/ exists; this is the register that says when what does exist runs out, and claims.test.ts refuses an “available” claim resting on an expired record.',
  },
  {
    id: 'proof',
    category: 'Proof calendar',
    path: 'docs/PROOF-CALENDAR.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: [],
    note: 'The schedule for producing the evidence needed to sell: three months, then quarterly, each item naming the artifact it files and the register rows it moves.',
  },
  {
    id: 'war-room',
    category: 'Launch war room',
    path: 'docs/LAUNCH-WAR-ROOM.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/LAUNCH-READINESS-COUNCIL.md'],
    note: 'The daily board for the final weeks before launch: thirteen items, each with an owner and the document it is read from.',
  },
  {
    id: 'first-year',
    category: 'Company first-year measures',
    path: 'docs/COMPANY-FIRST-YEAR-MEASURES.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-005', 'D-009'],
    alsoRead: ['ANALYTICS.md'],
    note: 'What "lead the category" means in the first twelve months, as measures with sources. No target is set here; each is a founder decision recorded in the log.',
  },
  {
    id: 'council',
    category: 'Launch readiness council',
    path: 'docs/LAUNCH-READINESS-COUNCIL.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/GO-NO-GO-CHECKLIST.md', 'docs/LAUNCH-DECISIONS.md'],
    note: 'The seats, the gates and `decide()`. Every owner on this page is one of its seats.',
  },
  {
    id: 'rhythm',
    category: 'Operating rhythm',
    path: 'docs/operating-model/OPERATING-RHYTHM.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/operating-model/README.md'],
    note: 'Weekly, monthly, quarterly and annual reviews, each with a written output. The proof calendar’s quarterly items are rows of its quarterly table.',
  },
  {
    id: 'gates',
    category: 'Engineering gates',
    path: 'REGRESSION-CHECKLIST.md',
    status: 'current',
    owner: 'engineering',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-010'],
    alsoRead: ['CLAUDE.md', '.github/pull_request_template.md'],
    note: 'The checks every change passes and the baseline figures. CLAUDE.md is the working agreement for agents; the pull-request template is what a reviewer sees.',
  },
  {
    id: 'documentation',
    category: 'Documentation system',
    path: 'docs/documentation/README.md',
    status: 'current',
    owner: 'engineering',
    version: 1,
    lastReviewed: '2026-10-04',
    nextReview: '2027-01-04',
    supersedes: [],
    decisions: ['D-1188'],
    alsoRead: ['docs/README.md', 'docs/documentation/QUALITY-GATES.md', 'docs/documentation/OWNERSHIP-AND-REVIEW.md'],
    note: 'The card every governed page opens with, the gate that holds them, the change obligation (docs:impact) and the generated index. About three hundred older documents are not governed by it and are not moved.',
  },
  {
    id: 'analytics',
    category: 'Product analytics',
    path: 'ANALYTICS.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-005'],
    alsoRead: ['docs/PRODUCT-ANALYTICS-DATA-ETHICS.md'],
    note: 'Three marks and nothing else; a fourth is a decision. Every first-year measure that needs a new mark lands the way D-005 says.',
  },
  {
    id: 'subprocessors',
    category: 'Subprocessor register',
    path: 'docs/SUBPROCESSORS.md',
    status: 'current',
    owner: 'privacy',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: [],
    note: 'Every third party that touches data, and what it sees. The quarterly vendor review on the proof calendar reads it.',
  },
  {
    id: 'expansion',
    category: 'Strategic expansion register',
    path: 'docs/STRATEGIC-EXPANSION-REGISTER.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['DECISIONS §1'],
    alsoRead: ['docs/PRODUCT-ROADMAP.md'],
    note: 'Rendered from app/src/lib/expansionregister.ts: the phased expansion, each phase gated. The plan of record says what is built next; this says what may be entered at all.',
  },
  {
    id: 'communities',
    category: 'Communities register',
    path: 'docs/COMMUNITIES-REGISTER.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/COMMUNITY-PRIVACY-MODEL.md', 'docs/CAMPUS-MODERATION-SOP.md', 'docs/ETHICAL-ENGAGEMENT-AND-NOTIFICATIONS.md'],
    note: 'Rendered from app/src/lib/communitiesregister.ts and app/src/community/governance.ts: every item of the four community blueprints, in their five phases, with the readiness brief, the launch gates, the severity ladder and the forbidden mechanics. The expansion register says what may be entered at all; this says where the community layer stands.',
  },
  {
    id: 'connect',
    category: 'Semester Connect register',
    path: 'docs/SEMESTER-CONNECT-REGISTER.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: [],
    alsoRead: ['docs/COMMUNITIES-REGISTER.md'],
    note: 'Rendered from app/src/lib/connectregister.ts, app/src/community/connect.ts and app/src/lib/gtm/social.ts: every addition the community brief of 29 September asks for — ten in the app, six on the company site, the social media ecosystem, fourteen controls and the rollout order — read against the tree, each row naming the communities-register item it overlaps. The communities register says where the blueprints stand; this says where the brief that followed them stands.',
  },
  {
    id: 'supply-chain',
    category: 'Supply-chain policy',
    path: 'docs/SUPPLY-CHAIN.md',
    status: 'current',
    owner: 'engineering',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: [],
    note: 'Rendered from app/src/lib/supplychain.ts and the lockfiles; the test fails on a licence or Action nobody has named, and every deploy carries an SBOM.',
  },
  {
    id: 'security-policy',
    category: 'Security policy',
    path: 'SECURITY.md',
    status: 'current',
    owner: 'security',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['ADR-0002'],
    alsoRead: ['SECRETS.md', 'docs/trust/SECURITY-WHITEPAPER.md'],
    note: 'How a report is made and handled, the severity model with its remediation targets, and what is disclosed; app/src/lib/security.test.ts holds it to the variables the Edge Functions read, to the patch policy and to the published security.txt.',
  },
  {
    id: 'services',
    category: 'Service expansion register',
    path: 'docs/SERVICE-EXPANSION-REGISTER.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-111'],
    alsoRead: ['docs/TRANSFER-TRANSITION-HUB.md', 'docs/BASIC-NEEDS-NAVIGATOR.md', 'docs/STRATEGIC-EXPANSION-REGISTER.md'],
    note: 'Rendered from app/src/lib/serviceregister.ts: the twenty-six service layers beyond coursework, each capability marked present or absent in the tree, the twelve questions a proposed service answers, and the strategic sequence. The transfer hub and the basic-needs navigator, its first two, have pages of their own held to the launchpad, the pathways, the support directory and the transfer_evaluations constraint.',
  },
  {
    id: 'module-privacy',
    category: 'Module privacy model',
    path: 'docs/MODULE-PRIVACY-MODEL.md',
    status: 'current',
    owner: 'privacy',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-111', 'D-037'],
    alsoRead: ['docs/trust/FERPA-CONSENT-WORKFLOW.md', 'docs/CONSENT-SHARING-DESIGN.md', 'docs/ROLE-LAUNCH-REGISTER.md'],
    note: 'Rendered from app/src/lib/governance/module-privacy.ts: what each module holds by default and when staff see it, the role matrix held to app_roles, the share screen, the authority boundaries, the risk controls, the twelve launch gates and the governance council. The FERPA consent workflow behind the share screen is held field by field to the share tables.',
  },
  {
    id: 'ai-assurance',
    category: 'AI assurance',
    path: 'docs/operating-model/AI-ASSURANCE.md',
    status: 'current',
    owner: 'trust',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-111'],
    alsoRead: ['docs/operating-model/AI-LIFECYCLE-GATES.md', 'docs/trust/AI-MODEL-TRAINING-AND-DATA-USE-POLICY.md', 'docs/operating-model/AI-GOVERNANCE-BOARD.md'],
    note: 'Rendered from app/src/lib/governance/ai-assurance.ts: the NIST AI RMF audit matrix with each row at its lifecycle gate, the AI 800-1 misuse-risk checklist, the evaluation risk tiers held to the intake refusals, the artifact set, and the release gate held to AI_RELEASE_GATE. AI 800-1 is a second public draft and is cited as voluntary guidance only. The no-training policy is a draft for counsel.',
  },
  {
    id: 'learning-register',
    category: 'Learning, assessment and gradebook register',
    path: 'docs/LEARNING-ASSESSMENT-GRADEBOOK-REGISTER.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-112'],
    alsoRead: ['docs/LMS-LEARNING-ROADMAP.md', 'docs/QTI-3-ASSESSMENT-AND-MIGRATION.md', 'docs/operating-model/AI-GRADING-AND-INTEGRITY.md'],
    note: 'Rendered from app/src/lib/learningregister.ts: the fourteen areas of a native, source-aware learning environment — course home to ethical analytics — each capability marked present or absent in the tree, the eighteen study tools and eight advanced features marked the same way, the AI modes held to the tutor’s own, the student grade view, the phases and the release criteria for consequential grading. The faculty side is present only as the labelled sandbox, and every mark that rests on it says so.',
  },
  {
    id: 'lms-matrix',
    category: 'LMS interoperability matrix',
    path: 'docs/LMS-INTEROPERABILITY-MATRIX.md',
    status: 'current',
    owner: 'engineering',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-112'],
    alsoRead: ['docs/INTEROPERABILITY-ROADMAP.md', 'docs/LTI-1.3-LAUNCH-RUNBOOK.md', 'docs/INTEGRATION-OPERATOR-RUNBOOK.md', 'GRADESCOPE-TURNITIN.md'],
    note: 'Rendered from app/src/lib/integration/lmsmatrix.ts: Canvas, Blackboard, Moodle and Brightspace across LTI 1.3, grade exchange, APIs, rate limits, pagination and events; the weighted scorecard and its gates; the Canvas scopes held to the key module; the registration record held field by field to lti_platform; the event processor, the adaptive client and the grade write at what the tree has; the Blackboard and Moodle checklists; and Semester’s own developer contract. Standards first, discovery second, proprietary APIs third.',
  },
  {
    id: 'qti',
    category: 'QTI 3 assessment content and migration',
    path: 'docs/QTI-3-ASSESSMENT-AND-MIGRATION.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-112'],
    alsoRead: ['docs/LEARNING-ASSESSMENT-GRADEBOOK-REGISTER.md', 'docs/LMS-LEARNING-ROADMAP.md'],
    note: 'Rendered from app/src/lib/assessment/qti.ts: QTI 3 as the content model — the principles, the interaction library held to the five question kinds the app has, the authoring flow, the item analytics and their prohibition, the AI item-generation workflow with its metadata held to the Question type and its controls, and the ten-phase migration programme with its toolchain and thresholds.',
  },
  {
    id: 'ai-grading',
    category: 'AI in grading and integrity',
    path: 'docs/operating-model/AI-GRADING-AND-INTEGRITY.md',
    status: 'current',
    owner: 'trust',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-112'],
    alsoRead: ['docs/operating-model/AI-ASSURANCE.md', 'docs/operating-model/AI-LIFECYCLE-GATES.md', 'GRADESCOPE-TURNITIN.md'],
    note: 'Rendered from app/src/lib/governance/grading-ai.ts: Gradescope, Turnitin and Copyleaks compared without a single accuracy number, the institution-controlled evaluation that does compare them, the procurement pass/fail rules, the roles AI may hold in assessment at their lifecycle gates, the two rules at the AI intake — an automatic misconduct accusation is refused there as a disciplinary judgment; an AI-only grade is refused by nothing — and the twelve fairness controls, every tested one the sandbox.',
  },
  {
    id: 'one-system',
    category: 'One-system platform grammar',
    path: 'docs/ONE-SYSTEM-PLATFORM-GRAMMAR.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-112'],
    alsoRead: ['docs/design/SEMESTER-UI-CONSTITUTION.md', 'docs/DO-NOT-BUILD.md', 'ops/operations-console/README.md'],
    note: 'Rendered from app/src/lib/onesystem.ts: what makes Semester one system — the nine areas held to the app’s roots, the object envelope, the trust pattern held to the provenance words, the action model, the notification centre, search, the Me centre held to its control rows, the operations console views, the twelve consistency release gates, the eleven foundations and the seven relationship rules — each at what the tree has. The foundations exist as parts; the page says what to converge.',
  },
  {
    id: 'one-operating-system',
    category: 'One operating system',
    path: 'docs/ONE-OPERATING-SYSTEM.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: '2026-09-29',
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-125', 'D-003'],
    alsoRead: ['docs/ONE-SYSTEM-PLATFORM-GRAMMAR.md', 'docs/PUBLIC-SITE.md', 'docs/expansion/ROUTE-AND-FEATURE-CROSSWALK.md'],
    note: 'Rendered from app/src/lib/oneos.ts: the two briefs that say what makes Semester different — everything from the start, one central operating system — held to the tree: the positioning printed as written, the five destinations held to the tab bar’s labels, the shared objects and the vocabulary each at the module that carries it, the palette commands at the destinations that carry them (verb commands refused by the overlay’s own decision), the journeys, the event layer, the role homes, the console, the final test, the app, site and console additions, the company behind them and the ten that matter most. Two public pages print from it, each area at the weakest of the rows it rests on.',
  },
  {
    id: 'domain-replacement-register',
    category: 'Domain replacement register',
    path: 'docs/DOMAIN-REPLACEMENT-REGISTER.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: '2026-09-29',
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-143'],
    alsoRead: ['docs/UNIVERSITY-OS-ARCHITECTURE.md', 'docs/ONE-OPERATING-SYSTEM.md', 'docs/DATA-MIGRATION-PLAN.md'],
    note: 'Rendered from app/src/lib/replaceregister.ts: the four briefs that make replace-by-domain the destination — fourteen domains from connect-first role to native replacement, the fifteen replaceability requirements, the six phases, the bounded areas, today’s architecture principle with the seven source states and the hold categories, seventeen registration, LMS and service expansions, and what an institution needs to retire a system. Whether any domain can be retired into Semester is computed from the requirements; today none can.',
  },
  {
    id: 'definer-rls-register',
    category: 'Security Definer and RLS register',
    path: 'docs/DEFINER-RLS-REGISTER.md',
    status: 'current',
    owner: 'security',
    version: 1,
    lastReviewed: '2026-09-29',
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-127'],
    alsoRead: ['supabase/grants.check.sql', 'supabase/rls-coverage.check.sql', 'docs/architecture/0002-rls-is-the-authorization-boundary.md'],
    note: 'Rendered from app/src/lib/definerregister.ts: the architecture audit’s first artifact. Every security definer function a signed-in account can call — derived from the migrations and the grants allowlist, 151, the same set production’s advisor lists — in the audit’s seven categories, each held to the literal checks its body makes; and the advisor’s 45 policy-less tables, each held to row-level security, no policy and no client grant. The reading of 29 September, the fault it found in gtm_pilot_problems and what it leaves open.',
  },
  {
    id: 'reinforcement-register',
    category: 'Reinforcement register',
    path: 'docs/REINFORCEMENT-REGISTER.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: '2026-09-29',
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-133'],
    alsoRead: ['docs/MARKET-LEADERSHIP.md', 'docs/ONE-OPERATING-SYSTEM.md', 'docs/trust/COMPLIANCE-CROSSWALK.md'],
    note: 'Rendered from app/src/lib/reinforceregister.ts and app/src/lib/ops/operatingmodel.ts: seven briefs of 29 September on what else would make Semester the leader and the benchmark, read against the tree as one register — each row citing every brief item that asks for it and the oneos, leadership or Connect item it is the same as — with the operating model’s ten product areas owned by seats, the compliance playbook’s P0 blockers, the module scorecard and its fully-built gate, the final checklists pointed at the sets that answer them, and where a brief and the tree disagree.',
  },
  {
    id: 'launch-completeness',
    category: 'Launch completeness',
    path: 'docs/LAUNCH-COMPLETENESS.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: '2026-09-29',
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-137'],
    alsoRead: ['docs/DEFINITION-OF-DONE.md', 'docs/market-readiness/HECVAT_READINESS.md', 'docs/GO-NO-GO-CHECKLIST.md', 'docs/trust/PILOT-AGREEMENT-OUTLINE.md'],
    note: 'Rendered from app/src/lib/launchcompleteness.ts: the three briefs of 29 September on university launch readiness and the complete company, held item by item. The HECVAT tracker in seven domains with a council seat and a readiness control on every row, the registration and LMS go-live checklists, the student-data migration inventory, artifacts, field-mapping template, parallel run and guardrails, the Registration and Path pilot with its exclusions and attachments, the support table and packages held to the plans and the deal desk, the per-pilot command center on PilotPlan, the thirty-one-line final gate, the nine claim words on the claims register, and the documents, Trust Room and site pages each at what carries it. The pilot’s 12–26 weeks is held to the code’s 26 (D-134).',
  },
  {
    id: 'definition-of-done',
    category: 'Semester Definition of Done',
    path: 'docs/DEFINITION-OF-DONE.md',
    status: 'current',
    owner: 'product',
    version: 1,
    lastReviewed: '2026-09-29',
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-137'],
    alsoRead: ['docs/operating-model/QUALITY-MANAGEMENT.md', 'docs/LAUNCH-COMPLETENESS.md', 'docs/EMPTY-LOADING-ERROR-SUCCESS-STATES.md'],
    note: 'Rendered from app/src/lib/launchcompleteness.ts: the one standard every feature, launch, contract, integration and claim must meet — nine questions, each beside where the tree already asks it; the launch acceptance rule; the twelve core journeys, each held to its tests; and the eleven states every journey needs. The engineering checklist a pull request meets stays in QUALITY-MANAGEMENT; this is the question behind it.',
  },
  {
    id: 'k12-requirements',
    category: 'K–12 requirements',
    path: 'docs/k12/K12-REQUIREMENTS.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: '2026-09-29',
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-139', 'D-140'],
    alsoRead: ['docs/FERPA-COPPA-1EDTECH-READINESS.md', 'docs/trust/COMPLIANCE-CROSSWALK.md', 'docs/REINFORCEMENT-REGISTER.md'],
    note: 'Rendered from app/src/lib/k12/requirements.ts: what the K–12 edition must do for students 13 and over, the sixteen-item baseline a district’s student data waits on, each item with a status the tree can show and its evidence, and the questions only counsel can answer. It answers “may a district’s student data be accepted?” from the baseline, and today the answer is no.',
  },
  {
    id: 'launch-kit',
    category: 'SaaS launch kit',
    path: 'docs/SAAS-LAUNCH-KIT.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-113', 'D-009'],
    alsoRead: ['docs/operating-model/COMMERCIAL-GOVERNANCE.md', 'docs/trust/PILOT-AGREEMENT-OUTLINE.md', 'docs/LAUNCH-DECISIONS.md'],
    note: 'Rendered from app/src/lib/launchkit.ts: the company around the product — entity and formation, nine insurance coverages, the pilot agreement package and term sheet held to the pilot and deal-desk rules, twelve modules and the price bands beside the deal desk’s proposed minimums, the go-to-market plan on the sales stages, the governance council charter on the seats that already exist, and the first thirty days. A crosswalk, not a price book or a contract: nothing in it may be signed. The entity is held to the owner’s attestation of an LLC; the pilot term is held to the code’s 26 weeks (D-134).',
  },
  {
    id: 'operational-reality',
    category: 'Operational reality register',
    path: 'docs/OPERATIONAL-REALITY-REGISTER.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-113'],
    alsoRead: ['docs/MASTER-LAUNCH-READINESS-REGISTER.md', 'docs/GO-NO-GO-CHECKLIST.md', 'docs/PROOF-CALENDAR.md'],
    note: 'Rendered from app/src/lib/operationalreality.ts: what it takes to run the platform as a company — the master-plan fields and five workstreams on the seats, the company operating system, the customer-proof engine, five service tiers, the seventeen implementation-factory assets, the whole-platform readiness test, sixty-four production checks each with its guard or none, eighteen failure scenarios held to the edge-case, risk, game-day and maturity registers, the load and cost thresholds, data quality, support, implementation capacity, revenue operations, key-person resilience, the go-live dossier and the final twelve-line checklist, answered.',
  },
  {
    id: 'crosswalk',
    category: 'Compliance crosswalk',
    path: 'docs/trust/COMPLIANCE-CROSSWALK.md',
    status: 'current',
    owner: 'security',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-115'],
    alsoRead: ['docs/trust/EVIDENCE-REGISTER.md', 'docs/market-readiness/HECVAT_READINESS.md', 'docs/FERPA-COPPA-1EDTECH-READINESS.md', 'docs/operating-model/OPERATIONAL-MATURITY.md'],
    note: 'Rendered from app/src/lib/trust/compliance-crosswalk.ts: HECVAT 4, the four 1EdTech TrustEd Apps rubrics and the EDUCAUSE 2026 priorities as one control library with three views, every domain resting on rows of the four registers and every 0–4 score computed from their statuses by the test. The ceiling is 2 until docs/evidence/ exists. Also Semester’s own intake tier, the evidence package a high-tier vendor owes, the launch gates and the AI overlay. Neither HECVAT nor a TrustEd rubric is a certification; Semester has completed neither.',
  },
  {
    id: 'leadership',
    category: 'Market leadership register',
    path: 'docs/MARKET-LEADERSHIP.md',
    status: 'current',
    owner: 'founder',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: QUARTERLY,
    supersedes: [],
    decisions: ['D-115'],
    alsoRead: ['ops/strategic-boundaries/README.md', 'docs/DO-NOT-BUILD.md', 'docs/COMPANY-FIRST-YEAR-MEASURES.md', 'docs/90-DAY-LAUNCH-PROGRAM.md'],
    note: 'Rendered from app/src/lib/ops/leadership.ts: the fourteen plays, the thirteen one-X promises and the shared-services rule, the revenue lines and the lines not crossed, the friction index against the first-year measures, No Wrong Door against the help routes, the Launch System against the ninety-day programme, the benchmark test, and the faculty playbook — each pointed at what the tree holds, with a standing. Nothing on it says Semester is a whole platform; the count of promises kept is the finding.',
  },
  {
    id: 'readiness-pack',
    category: 'Operational readiness pack',
    path: 'docs/OPERATIONAL-READINESS-PACK.md',
    status: 'current',
    owner: 'engineering',
    version: 1,
    lastReviewed: REVIEWED,
    nextReview: MONTHLY,
    supersedes: [],
    decisions: ['D-115'],
    alsoRead: ['docs/LAUNCH-READINESS-COUNCIL.md', 'docs/RUNBOOKS.md', 'docs/operating-model/OPERATING-RHYTHM.md', 'docs/PROOF-CALENDAR.md'],
    note: 'Rendered from app/src/lib/ops/readiness-pack.ts: the five workstreams and nine decision domains as council seats, the seven pillars of production safety with every checklist item resting on register rows and launch gates and scored by the test, the dependency register (nothing tested), the eighteen minimum runbooks and what stands in for each, the launch gate whose verdict is computed — NO-GO today — the review packet, the sign-off record (nothing signed), the cadences and the first twelve initiatives. It adds no gate to the twelve of launchreadiness.ts; it reads them.',
  },
  {
    id: 'pia',
    category: 'Privacy impact assessment',
    path: 'docs/operating-model/PRIVACY-IMPACT-ASSESSMENT.md',
    status: 'current',
    owner: 'privacy',
    version: 1,
    lastReviewed: '2026-09-29',
    nextReview: '2026-10-29',
    supersedes: [],
    decisions: ['D-123'],
    alsoRead: ['docs/operating-model/RISK-GOVERNANCE.md', 'docs/PRODUCT-ANALYTICS-DATA-ETHICS.md', 'docs/MODULE-PRIVACY-MODEL.md', 'RETENTION.md'],
    note: 'Rendered from app/src/lib/governance/pia.ts: the eleven questions a surface that touches student data answers before it ships, seven surfaces answered against the tree (support tickets, beta feedback, the pilot figures, AI conversations, billing, the academic-record ledger, student accounts) with the answers a test holds told apart from the ones only written, six surfaces owed, and the gate line the pull-request template asks of every new module, held there by the test. The privacy seat is vacant; the answers are the founder’s reading until it reads them.',
  },
  {
    id: 'ai-playbook',
    category: 'AI integration playbook',
    path: 'docs/operating-model/AI-INTEGRATION-PLAYBOOK.md',
    status: 'current',
    owner: 'trust',
    version: 1,
    lastReviewed: '2026-09-29',
    nextReview: '2026-12-29',
    supersedes: [],
    decisions: ['D-131', 'D-135'],
    alsoRead: ['docs/operating-model/AI-ASSURANCE.md', 'docs/operating-model/AI-LIFECYCLE-GATES.md', 'docs/trust/DPA-CHECKLIST.md', 'docs/ONBOARDING-AND-CONTEXTUAL-HELP.md'],
    note: 'Rendered from app/src/lib/governance/ai-playbook.ts: the ten agentic workflows with their action tier, prohibitions held to the intake refusals and ROI scorecards; the human-confirmation matrix held to its own tiers; the four data classes checked against what the classification gate does to each tier; the vendor scorecard as code (scoreVendor), with every AI subprocessor on it and none scored; onboarding held to FirstGoal; and the definition of done held to AI_RELEASE_GATE. Most workflows are tested as non-AI workflows and have no agent yet; the page says so.',
  },
];

/**
 * The permanent rule on scope, and the questions every addition answers
 * before it is built. Held to the pull-request template by the test, so the
 * questions are asked where the change is reviewed rather than remembered.
 */
export const SCOPE_RULE =
  'No new module launches unless it replaces, improves, or connects an existing student or institution workflow with measurable value.';

export const SCOPE_QUESTIONS: readonly string[] = [
  'What does this replace?',
  'What student decision does it clarify?',
  'What institution decision does it improve?',
  'What data does it require?',
  'Who owns it?',
  'How is it supported?',
  'How is it tested?',
  'How does it fail?',
  'How is it removed if it does not work?',
];

/** Directories whose contents are records of a moment, never the current version of anything. */
export const ARCHIVED = ['chats/', 'docs/superpowers/', 'docs/institutional-rollout/generated/', 'project/'];

export const bySlug = (id: string): Source => {
  const s = SOURCES.find((x) => x.id === id);
  if (!s) throw new Error(`no source ${id}`);
  return s;
};
