/**
 * A video call, as arithmetic.
 *
 * The app already had the two things a study group needs and neither of the
 * two it wanted: a room per class you can type into (`lib/classmates.ts`) and
 * a shared list for a group project (`lib/groupwork.ts`), and then everybody
 * left the app to be in the same place at the same time. A call was the one
 * part of a semester that happened entirely somewhere else — a link pasted
 * into a group chat, a code nobody could find at 8:58, a meeting that had no
 * relationship to the deadline it was about.
 *
 * So: a call, inside the app, that knows what it is for.
 *
 * Everything here is pure and tested, and that is most of what a call is.
 * `lib/mesh.ts` decides who connects to whom; `lib/rtc.ts` is the browser
 * half — cameras, peer connections, the signalling channel — and is the only
 * part of this feature that cannot be run in a test.
 *
 * ## What is borrowed, and from which
 *
 * From Zoom: a code you can read down a phone, a lobby with four things on it
 * rather than a form, and a gallery that packs tiles rather than stacking
 * them. From Google Meet: the green room — you see yourself, pick your camera
 * and your microphone and *then* arrive, instead of joining a call and finding
 * out you are muted. The shape of the code is Meet's too, three-four-three,
 * for the reason Meet chose it: it survives being read aloud.
 *
 * From neither: a call belongs to a course and to a deadline. A scheduled one
 * is an ordinary appointment in the calendar — see `whereFor` below — so it
 * shows up on Today and in the week beside the thing it is about, rather than
 * in a second app that does not know what a semester is.
 */

/**
 * The alphabet a code is drawn from — twenty letters, no vowels.
 *
 * Meet uses all twenty-six, which is fine when a code is generated by a
 * company with a support page. Dropping the vowels does two things worth
 * having here: three random consonants cannot spell a word somebody has to
 * read out to their study group, and the pairs people mishear on a phone —
 * `a`/`e`, `i`/`e`, `o`/`u` — cannot occur. `l` goes with them because it is
 * `1` and `I` on half the fonts in the world.
 */
export const LETTERS = 'bcdfghjkmnpqrstvwxz';

/** Three, four, three — the shape you can say down a phone. */
const SHAPE = [3, 4, 3];

/** The most people one mesh call will admit. See `load` below for why. */
export const FULL = 12;

/** Past this many, the mesh is doing more work than a laptop enjoys. */
export const ROOMY = 6;

/**
 * A new code.
 *
 * `random` is injectable so the test can produce a known code rather than
 * asserting on a shape and hoping. Nothing about this is a secret — a code is
 * a name, and the fact that anybody holding one can walk in is said on the
 * screen rather than implied by its length.
 */
export function newCode(random: () => number = Math.random): string {
  return SHAPE.map((n) =>
    Array.from({ length: n }, () => LETTERS[Math.floor(random() * LETTERS.length) % LETTERS.length])
      .join(''),
  ).join('-');
}

/** Whether a string is a code this app would have made. */
export function validCode(code: string): boolean {
  return new RegExp(`^[${LETTERS}]{3}-[${LETTERS}]{4}-[${LETTERS}]{3}$`).test(code);
}

/**
 * A code out of whatever somebody pasted.
 *
 * People paste the link, the code with its hyphens, the code without them, the
 * code with a capital on the front because their phone put one there, and a
 * whole line of a message with the code somewhere in the middle. All of those
 * are the same intent and all of them work.
 *
 * Two passes, in this order. A hyphenated code anywhere in the text is taken
 * as written — that is the shape this app produces, and finding it inside a
 * sentence is what makes "join bcd-fghj-kmn at four" paste correctly. Failing
 * that, the letters are taken on their own and the *last* ten win, because a
 * pasted link ends with the code and begins with an origin full of letters.
 *
 * Returns '' rather than guessing: an empty code is a Join button that stays
 * disabled, which is the honest answer to ten characters that are not a code.
 */
export function normaliseCode(text: string): string {
  const written = spelled(text);
  if (written) return written;
  const letters = (text ?? '').toLowerCase().replace(new RegExp(`[^${LETTERS}]+`, 'g'), '');
  if (letters.length < 10) return '';
  const ten = letters.slice(-10);
  const code = `${ten.slice(0, 3)}-${ten.slice(3, 7)}-${ten.slice(7)}`;
  return validCode(code) ? code : '';
}

/**
 * A code written out with its hyphens, anywhere in a piece of text.
 *
 * The strict half of the pair above, and the one anything reading *prose*
 * uses. The lenient pass cannot be let near a sentence somebody wrote: ten
 * consonants in a row happen in ordinary writing once you have thrown the
 * vowels away, and a note reading "bring the stats printout" is not a call.
 */
export function spelled(text: string): string {
  const found = new RegExp(`(?:^|[^a-z])([${LETTERS}]{3}-[${LETTERS}]{4}-[${LETTERS}]{3})(?![a-z])`, 'i')
    .exec(text ?? '');
  const code = (found?.[1] ?? '').toLowerCase();
  return validCode(code) ? code : '';
}

/**
 * The link you send somebody.
 *
 * A hash address, like every other link in this app, and for the same reason —
 * see `lib/route.ts`. `origin` is passed rather than read off `location` so
 * this is testable and so the caller decides whether it is sharing an address
 * on this machine or the deployed one.
 */
export function linkTo(code: string, origin: string): string {
  const clean = origin.replace(/#.*$/, '').replace(/\/+$/, '');
  return `${clean}/#/call/${code}`;
}

/**
 * How much work a mesh of this many people is.
 *
 * There is no server mixing these streams — every person sends their own
 * camera to every other person directly, which is what makes a call possible
 * at all without renting one. The cost is that the work grows with the room:
 * each person uploads `n − 1` streams and downloads `n − 1`, so the whole call
 * carries `n × (n − 1)` of them.
 *
 * Four people is twelve streams and unremarkable. Eight is fifty-six, which is
 * a warm laptop and a phone that gives up. The screen says this plainly at
 * `ROOMY` rather than discovering it at nine, and `FULL` is where it stops
 * admitting people — a call that is bad for everybody is worse than a call one
 * person could not get into.
 */
export function load(people: number): { each: number; total: number; tight: boolean; full: boolean } {
  const n = Math.max(0, Math.floor(people));
  const each = Math.max(0, n - 1);
  return { each, total: n * each, tight: n > ROOMY, full: n >= FULL };
}

export interface Box {
  width: number;
  height: number;
}

export interface Grid {
  cols: number;
  rows: number;
  /** One tile, at the size that fits. */
  width: number;
  height: number;
}

/**
 * The gallery: how to cut a box into `count` tiles.
 *
 * This is the one piece of a video call that is genuinely arithmetic, and
 * getting it wrong is the difference between Zoom's gallery and a column of
 * letterboxes. The naive answer — a square-ish grid, `ceil(sqrt(n))` across —
 * is wrong for the shape people hold: four tiles on a phone want one column
 * and four rows, and four tiles on a laptop want two by two. The grid depends
 * on the *box*, not only on the count.
 *
 * So every column count from one to `count` is tried, the largest tile each
 * would give is worked out, and the winner is the one with the most area. That
 * is a loop of at most twelve iterations and it is exact, which is worth more
 * than a clever closed form nobody can check.
 *
 * Tiles keep `aspect` — 16:9, what a camera gives — rather than filling their
 * cell, because a stretched face is the one rendering fault everybody notices.
 */
export function grid(count: number, box: Box, aspect = 16 / 9, gap = 8): Grid {
  if (count <= 0 || box.width <= 0 || box.height <= 0) {
    return { cols: 0, rows: 0, width: 0, height: 0 };
  }
  let best: Grid = { cols: 1, rows: count, width: 0, height: 0 };
  for (let cols = 1; cols <= count; cols++) {
    const rows = Math.ceil(count / cols);
    const cellW = (box.width - gap * (cols - 1)) / cols;
    const cellH = (box.height - gap * (rows - 1)) / rows;
    if (cellW <= 0 || cellH <= 0) continue;
    // Fit the 16:9 tile inside the cell — whichever of the two runs out first.
    const width = Math.min(cellW, cellH * aspect);
    const height = width / aspect;
    if (width * height > best.width * best.height) best = { cols, rows, width, height };
  }
  return best;
}

/** One person in the call, as the stage needs to see them. */
export interface Peer {
  id: string;
  name: string;
  /** You. Drawn differently, and sorted differently — see `ordered`. */
  self?: boolean;
  joinedAt: number;
  camera: boolean;
  muted: boolean;
  /** When the hand went up, or 0. Ordered by it, so first up is first seen. */
  hand: number;
  sharing: boolean;
  /** The last moment this person was talking. See `talk` below. */
  spokeAt: number;
}

/** How long after a word somebody still counts as "who is talking". */
export const RECENT = 30_000;

/**
 * The order the tiles are drawn in.
 *
 * A gallery of nine is nine equal squares until the moment it is not: somebody
 * shares their screen, somebody puts a hand up, somebody starts answering the
 * question. Every call app has an answer to that and they are all roughly this
 * one, in this order:
 *
 *   1. Whoever you pinned. An explicit choice outranks every guess below it.
 *   2. Whoever is sharing a screen — that is the thing being talked about.
 *   3. Hands, oldest first. A hand up is a person waiting for a turn, and
 *      reordering that queue by who spoke last is exactly backwards.
 *   4. Whoever has spoken in the last half minute, most recent first.
 *   5. Cameras on before cameras off, so a screen of initials sinks.
 *   6. Then the order people arrived, which never changes under anybody.
 *
 * And you sink below anybody you tie with. Your own face is the one tile you
 * do not need to see, and taking the top-left of somebody else's gallery
 * because you joined first is the small rudeness this avoids.
 */
export function ordered(peers: Peer[], now: number, pinned = ''): Peer[] {
  const rank = (p: Peer): number[] => [
    p.id === pinned ? 0 : 1,
    p.sharing ? 0 : 1,
    p.hand > 0 ? 0 : 1,
    p.hand > 0 ? p.hand : 0,
    now - p.spokeAt < RECENT ? 0 : 1,
    now - p.spokeAt < RECENT ? -p.spokeAt : 0,
    p.camera ? 0 : 1,
    p.self ? 1 : 0,
    p.joinedAt,
  ];
  return [...peers].sort((a, b) => {
    const x = rank(a);
    const y = rank(b);
    for (let i = 0; i < x.length; i++) if (x[i] !== y[i]) return x[i] - y[i];
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
  });
}

/**
 * The big tile in speaker view, or nothing.
 *
 * The first of `ordered`, with one refusal: it will not put *you* in the large
 * frame while there is anybody else in the call. Speaker view is for watching
 * the person talking, and in a room of two where the other person is silent
 * the honest answer is their tile, not a mirror.
 */
export function spotlight(peers: Peer[], now: number, pinned = ''): Peer | null {
  const all = ordered(peers, now, pinned);
  if (all.length === 0) return null;
  const first = all[0];
  if (!first.self || all.length === 1 || first.id === pinned) return first;
  return all.find((p) => !p.self) ?? first;
}

/** What `talk` remembers between samples. */
export interface Talk {
  speaking: boolean;
  /** When this run of speech began, for anything that wants its length. */
  since: number;
  /** The last moment there was sound. The hold below is measured from it. */
  heard: number;
}

/** Loud enough to start counting as speech. */
export const LOUD = 0.055;
/** Quiet enough to stop — lower than `LOUD`, which is the whole point. */
export const QUIET = 0.028;
/** How long after the last sound a talker is still the talker. */
export const HOLD = 900;

export const SILENT: Talk = { speaking: false, since: 0, heard: 0 };

/**
 * Whether this person is talking, from the loudness of one audio frame.
 *
 * Two devices sit between a voice and this number — a microphone with its own
 * gain and a browser with its own filtering — so any single threshold
 * flickers. Two of them do not: it takes `LOUD` to start and a drop below
 * `QUIET` to stop, and the gap between them is what keeps a steady speaker
 * from strobing on every consonant.
 *
 * The hold is the second half, and it is measured from the last sound rather
 * than from the start of the sentence. Speech has gaps in it — a breath is
 * 300ms of near-silence in the middle of a clause — so a talker stays the
 * talker for `HOLD` after the room goes quiet. Timed from the *start*
 * instead, as this was written once, a long answer switches itself off
 * mid-sentence; timed from each quiet frame, it never switches off at all.
 */
export function talk(was: Talk, level: number, now: number): Talk {
  if (level >= LOUD) {
    return { speaking: true, since: was.speaking ? was.since : now, heard: now };
  }
  if (!was.speaking) return was;
  // Between the thresholds is still sound, so it keeps the hold alive.
  if (level > QUIET) return { ...was, heard: now };
  return now - was.heard >= HOLD ? { speaking: false, since: now, heard: was.heard } : was;
}

/**
 * How long the call has been running — "0:07", "12:34", "1:02:03".
 *
 * Hours appear only once there is one, because a study call is forty minutes
 * and "0:41:12" is three characters of nothing in the corner of every screen.
 */
export function elapsed(ms: number): string {
  const total = Math.max(0, Math.floor(ms / 1000));
  const s = total % 60;
  const m = Math.floor(total / 60) % 60;
  const h = Math.floor(total / 3600);
  const pad = (n: number) => String(n).padStart(2, '0');
  return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

/**
 * Where a scheduled call lives: in the calendar, as an appointment.
 *
 * This feature adds nothing to the saved shape of an account, and that is a
 * decision rather than a shortcut. A call at four on Thursday is an
 * appointment at four on Thursday — it belongs in the rail with your classes,
 * on Today, in the week ahead, in the export and in the sync, and every one of
 * those already works for appointments and would have had to be taught about
 * calls one screen at a time.
 *
 * The code rides in `where`, which is the field that answers "where is this".
 * For a call, the answer is a code.
 */
export function whereFor(code: string): string {
  return `Call · ${code}`;
}

/**
 * The code out of an appointment, or ''.
 *
 * Reads `where` first and then `note`, so a call somebody typed the link into
 * by hand is still a call the calendar can offer a Join button for. Anything
 * that is not a code comes back empty, which is how an ordinary appointment —
 * a haircut, an advisor meeting — stays an ordinary appointment.
 */
export function codeOf(a: { where?: string | null; note?: string | null }): string {
  return spelled(a.where ?? '') || spelled(a.note ?? '');
}

/**
 * What to call a call before anybody has named it.
 *
 * A course code where there is one, because that is what somebody will be
 * looking for in their calendar on Thursday, and a plain word where there is
 * not. Never the code: a title reading "bcd-fghj-kmn" tells you nothing that
 * the line under it does not already say.
 */
export function nameFor(courseCode: string): string {
  const code = courseCode.trim();
  return code ? `${code} study call` : 'Study call';
}
