import {describe,it,expect} from 'vitest';
import {allowsFamilyRequest,type FamilyGrant,type FamilyRequest} from '@semester/institution';
import {EMPTY_FAMILY,newFamilyMember,newFamilyItem,readFamily,familyPreview} from './family';
import {EMPTY_PATHWAY,newProgram,newPathwayProject,readPathway,readPrograms,netProgramCost,programReadiness} from './pathway';
const request:FamilyRequest={institutionId:'school',studentId:'student',recipientId:'parent',category:'finances',resourceId:'invoice1',operation:'read'};
const grant:FamilyGrant={id:'grant',...request,access:'view',resourceIds:['invoice1'],acceptedAt:10,expiresAt:100,revokedAt:null};
describe('family authorization boundaries',()=>{
 it('requires matching institution, student, recipient, category and resource',()=>{expect(allowsFamilyRequest(grant,request,20)).toBe(true);for(const key of ['institutionId','studentId','recipientId','category','resourceId'])expect(allowsFamilyRequest(grant,{...request,[key]:'other'},20)).toBe(false);});
 it('denies pending, expired, revoked and invalid grants',()=>{for(const change of [{acceptedAt:null},{acceptedAt:30},{expiresAt:20},{expiresAt:NaN},{revokedAt:19},{access:'none' as const}])expect(allowsFamilyRequest({...grant,...change},request,20)).toBe(false);});
 it('payment permission never reveals bills and never permits other category actions',()=>{const g={...grant,access:'payment' as const};expect(allowsFamilyRequest(g,request,20)).toBe(false);expect(allowsFamilyRequest(g,{...request,operation:'pay'},20)).toBe(true);expect(allowsFamilyRequest({...g,category:'academic'},{...request,category:'academic',operation:'pay'},20)).toBe(false);expect(allowsFamilyRequest(grant,{...request,operation:'pay'},20)).toBe(false);});
 it('local family preview starts empty and excludes other people and unselected categories',()=>{const a={...newFamilyMember(),name:'A'},b={...newFamilyMember(),name:'B'};const x={...newFamilyItem(a.id),title:'Check-in'};let l=readFamily({...EMPTY_FAMILY,members:[a,b],items:[x,{...newFamilyItem(b.id),title:'Private to B'}]});expect(familyPreview(l,a.id)).toEqual([]);a.permissions.communication='selected';l=readFamily({...l,members:[a,b]});expect(familyPreview(l,a.id).map(i=>i.title)).toEqual(['Check-in']);expect(familyPreview({...l,members:[{...a,revoked:true},b]},a.id)).toEqual([]);expect(familyPreview({...l,members:[{...a,expires:'2026-01-01'},b]},a.id,'2026-01-02')).toEqual([]);});
 it('rejects invalid dates and access choices without accepting corrupt backup data',()=>{const a={...newFamilyMember(),name:'A',expires:'2026-99-90'};expect(()=>readFamily({...EMPTY_FAMILY,members:[a]})).toThrow();a.expires='';a.permissions.academic='payment';expect(()=>readFamily({...EMPTY_FAMILY,members:[a]})).toThrow();});
});
describe('education continuity',()=>{
 it('changing stages preserves application and research preparation',()=>{const program={...newProgram(),school:'Example',program:'Biology'};const project=newPathwayProject('Thesis or dissertation');const next=readPathway({...EMPTY_PATHWAY,stage:'Alumnus',programs:[program],projects:[project]});expect(next.programs[0]).toEqual(program);expect(next.projects[0].steps.length).toBe(13);expect(next.projects[0].steps.every(s=>!s.done)).toBe(true);});
 it('computes cost from explicit estimates and identifies missing material',()=>{const p={...newProgram(),school:'A',program:'B',tuition:20000,living:10000,other:500,aid:1000,materials:[{id:'essay',title:'Essay',status:'Preparing' as const,due:''}]};expect(netProgramCost(p)).toBe(29500);expect(programReadiness(p)).toEqual({missing:1,hasDeadline:false,hasRequirements:false});});
 it('rejects unsafe catalog links, negative costs and duplicate identities',()=>{const p={...newProgram(),school:'A',program:'B'};for(const rows of [[{...p,url:'javascript:alert(1)'}],[{...p,aid:-1}],[p,p]])expect(()=>readPrograms(rows)).toThrow();});
});
