import type { Budget } from './rules';

/**
 * What each file is still owed, off the three scales. Generated — do not edit.
 *
 *     npm run lint:styles -- --fix
 *
 * measures the tree and rewrites this. It is a list of debts: a file that is
 * not here may have none at all, which is the rule new code is held to.
 *
 * Why it is a file per line rather than four numbers for the app, and why
 * that is stricter rather than looser, is written where the rule is —
 * `rules.ts`, under "Why it is counted per file". The short version is that
 * four shared numbers meant every branch in the repository wrote to the same
 * four lines, so every pair of branches conflicted here over a disagreement
 * neither of them had.
 */

export const BUDGET: Budget = {
  'App.tsx': { type: 3, leading: 1, space: 1, shorthand: 2 },
  'ai/Actions.tsx': { dim: 4 },
  'ai/Answer.tsx': { shorthand: 1, dim: 1 },
  'ai/AskAbout.tsx': { shorthand: 1 },
  'ai/Assistant.tsx': { type: 1 },
  'ai/Chat.tsx': { dim: 2 },
  'ai/Panel.tsx': { space: 1, shorthand: 1, dim: 1 },
  'ai/Threads.tsx': { dim: 4 },
  'ai/Turns.tsx': { space: 1, dim: 3 },
  'components/Adopting.tsx': { type: 1, space: 2, shorthand: 2, dim: 1 },
  'components/Appearance.tsx': { space: 1, shorthand: 4, dim: 2 },
  'components/Applying.tsx': { type: 3, leading: 2, space: 4, shorthand: 4 },
  'components/AskForTime.tsx': { shorthand: 1 },
  'components/Attendance.tsx': { type: 12, leading: 1, space: 3, shorthand: 3 },
  'components/Avatar.tsx': { leading: 1 },
  'components/BehindOffer.tsx': { type: 2, space: 2, shorthand: 1 },
  'components/Boundary.tsx': { dim: 2 },
  'components/BreakItUp.tsx': { type: 1, space: 1, shorthand: 3 },
  'components/CameBack.tsx': { type: 4, space: 5, shorthand: 4 },
  'components/Capacity.tsx': { type: 5, space: 3, shorthand: 10, dim: 1 },
  'components/Capture.tsx': { type: 2, space: 1, shorthand: 2 },
  'components/CheckIt.tsx': { type: 6, leading: 1, space: 7, shorthand: 3, dim: 1 },
  'components/Clashes.tsx': { leading: 1, space: 2, shorthand: 2 },
  'components/CloseTerm.tsx': { type: 2, space: 3, shorthand: 1 },
  'components/Credentials.tsx': { space: 5, dim: 1 },
  'components/Cutoffs.tsx': { type: 2, space: 1, shorthand: 2, dim: 1 },
  'components/DeadlineRow.tsx': { space: 1, shorthand: 1 },
  'components/Diagram.tsx': { type: 1 },
  'components/Dictate.tsx': { type: 2, space: 1 },
  'components/Drawing.tsx': { type: 3, space: 1, shorthand: 1 },
  'components/DropBy.tsx': { type: 4, leading: 1, space: 2, shorthand: 1 },
  'components/FigureCard.tsx': { type: 2, leading: 3, space: 4, shorthand: 1, dim: 2 },
  'components/FindPlace.tsx': { type: 7, leading: 2, space: 7, shorthand: 6, dim: 1 },
  'components/Fold.tsx': { shorthand: 2 },
  'components/Fresh.tsx': { type: 1, shorthand: 2 },
  'components/GpaScale.tsx': { type: 2, shorthand: 3 },
  'components/HomeWalk.tsx': { type: 1, leading: 1, space: 2, shorthand: 1 },
  'components/HourGrid.tsx': { type: 3, leading: 1, space: 1, shorthand: 1, dim: 2 },
  'components/HowLong.tsx': { type: 1, leading: 1, shorthand: 2 },
  'components/HowMuch.tsx': { type: 2, space: 2, shorthand: 1 },
  'components/InsightCards.tsx': { shorthand: 2, dim: 1 },
  'components/Insights.tsx': { type: 1, leading: 1, space: 1, shorthand: 2, dim: 2 },
  'components/Keys.tsx': { type: 1, shorthand: 3, dim: 1 },
  'components/KindKey.tsx': { type: 1, space: 1 },
  'components/LiveMap.tsx': { dim: 2 },
  'components/MarkClass.tsx': { type: 1, space: 2, shorthand: 1 },
  'components/MyRules.tsx': { type: 6, space: 2, shorthand: 2 },
  'components/NeedsKey.tsx': { dim: 1 },
  'components/NotYetOpened.tsx': { type: 3, leading: 1, space: 2, shorthand: 2 },
  'components/OfficeHours.tsx': { type: 2, leading: 1, space: 1, shorthand: 2 },
  'components/PiecesRow.tsx': { type: 3, space: 3, shorthand: 2, dim: 1 },
  'components/PostMortem.tsx': { type: 5, space: 3, shorthand: 2 },
  'components/Produced.tsx': { leading: 1, space: 1, shorthand: 1 },
  'components/ProjectFile.tsx': { type: 9, space: 3, shorthand: 3, dim: 1 },
  'components/PullDown.tsx': { leading: 1 },
  'components/PushSwitch.tsx': { type: 1 },
  'components/QuickAdd.tsx': { type: 5, leading: 1, space: 4, dim: 1 },
  'components/ReadingProgress.tsx': { type: 4, leading: 1, space: 6, shorthand: 6, dim: 1 },
  'components/RecordButton.tsx': { type: 8, leading: 1, space: 5, shorthand: 2, dim: 4 },
  'components/Replaced.tsx': { type: 1, shorthand: 3, dim: 1 },
  'components/ReviewSheet.tsx': { space: 3, shorthand: 2, dim: 3 },
  'components/Rework.tsx': { type: 4, leading: 2, space: 3, shorthand: 3, dim: 3 },
  'components/Ringing.tsx': { type: 2, space: 2 },
  'components/Running.tsx': { type: 1, space: 1, shorthand: 1 },
  'components/SampleMark.tsx': { type: 1, shorthand: 1, dim: 3 },
  'components/SayIt.tsx': { type: 2, space: 1, dim: 1 },
  'components/ScanIsbn.tsx': { type: 2 },
  'components/SchoolPicker.tsx': { type: 6, leading: 2, space: 8, shorthand: 4 },
  'components/ScoreField.tsx': { type: 1, leading: 1, space: 1 },
  'components/ShareCourse.tsx': { type: 1, space: 1 },
  'components/Snapshots.tsx': { type: 5, leading: 1, space: 3, shorthand: 2, dim: 2 },
  'components/StartToday.tsx': { type: 5, leading: 2, space: 7, shorthand: 4 },
  'components/StorageRoom.tsx': { type: 2, leading: 1, space: 2, dim: 1 },
  'components/Subscribe.tsx': { dim: 2 },
  'components/Suggested.tsx': { type: 3, leading: 1, space: 5, shorthand: 3, dim: 1 },
  'components/TabChooser.tsx': { type: 5, space: 2, shorthand: 7 },
  'components/TermSwitch.tsx': { type: 1 },
  'components/Timer.tsx': { type: 9, leading: 2, space: 6, shorthand: 11, dim: 1 },
  'components/TimerLine.tsx': { type: 2, space: 2, shorthand: 2 },
  'components/Trouble.tsx': { type: 1, space: 1, shorthand: 1 },
  'components/TypeToConfirm.tsx': { type: 3, space: 3, shorthand: 1, dim: 1 },
  'components/Undone.tsx': { shorthand: 2 },
  'components/UseSources.tsx': { type: 2 },
  'components/Walks.tsx': { type: 2, leading: 1, space: 1 },
  'components/WeekDue.tsx': { type: 2, leading: 1, space: 1, dim: 1 },
  'components/WeekGrid.tsx': { type: 3, leading: 1, shorthand: 1, dim: 1 },
  'components/Windows.tsx': { type: 2, leading: 1, space: 3, shorthand: 2 },
  'components/WorkWindows.tsx': { type: 4, shorthand: 3, dim: 1 },
  'components/YourCourses.tsx': { type: 2, space: 4, shorthand: 4 },
  'components/shell/Rows.tsx': { type: 3, leading: 2, space: 1, dim: 1 },
  'components/ui.tsx': { type: 2, space: 1, shorthand: 5 },
  'screens/Account.tsx': { type: 8, leading: 7, space: 4, dim: 8 },
  'screens/Activities.tsx': { type: 16, leading: 1, space: 5, shorthand: 9, dim: 4 },
  'screens/Ahead.tsx': { type: 12, leading: 5, space: 5, shorthand: 3, dim: 2 },
  'screens/Analyse.tsx': { type: 5, shorthand: 4, dim: 1 },
  'screens/Applying.tsx': { type: 13, leading: 1, space: 7, shorthand: 13 },
  'screens/Behind.tsx': { type: 6, leading: 2, space: 4, shorthand: 7 },
  'screens/Bill.tsx': { type: 4, leading: 3, space: 1, shorthand: 3, dim: 3 },
  'screens/Calendar.tsx': { type: 16, leading: 10, space: 15, shorthand: 15, dim: 8 },
  'screens/Clocks.tsx': { type: 8, leading: 1, space: 6, shorthand: 17, dim: 1 },
  'screens/Connect.tsx': { type: 8, leading: 1, space: 5, shorthand: 4, dim: 3 },
  'screens/Costs.tsx': { type: 4, leading: 2, space: 2, shorthand: 3, dim: 1 },
  'screens/Courses.tsx': { type: 10, leading: 2, space: 11, shorthand: 13, dim: 5 },
  'screens/Data.tsx': { shorthand: 4 },
  'screens/Deck.tsx': { type: 5, space: 6, shorthand: 2, dim: 1 },
  'screens/Degree.tsx': { type: 8, leading: 3, space: 6, shorthand: 12, dim: 1 },
  'screens/Draw.tsx': { type: 5, leading: 1, space: 2, shorthand: 1 },
  'screens/Drill.tsx': { type: 9, leading: 6, space: 14, shorthand: 7, dim: 2 },
  'screens/EditCourse.tsx': { type: 8, space: 7, shorthand: 4, dim: 2 },
  'screens/Essay.tsx': { type: 8, leading: 1, space: 5, shorthand: 6 },
  'screens/Exam.tsx': { type: 17, leading: 4, space: 16, shorthand: 8 },
  'screens/Export.tsx': { type: 4, leading: 1, space: 6, shorthand: 4, dim: 2 },
  'screens/Field.tsx': { type: 13, leading: 9, space: 11, shorthand: 7, dim: 10 },
  'screens/FirstRun.tsx': { type: 3, leading: 1, shorthand: 1, dim: 2 },
  'screens/Gap.tsx': { type: 4, leading: 3, space: 5, shorthand: 2, dim: 4 },
  'screens/GapOffer.tsx': { type: 3, leading: 1, space: 3, shorthand: 1, dim: 1 },
  'screens/Grades.tsx': { type: 8, leading: 2, space: 4, shorthand: 4, dim: 1 },
  'screens/Groupwork.tsx': { type: 11, leading: 3, space: 5, shorthand: 3, dim: 3 },
  'screens/Guess.tsx': { type: 6, leading: 3, space: 7, dim: 2 },
  'screens/Guide.tsx': { type: 26, leading: 18, space: 33, shorthand: 15, dim: 26 },
  'screens/Help.tsx': { shorthand: 3, dim: 1 },
  'screens/Housing.tsx': { type: 6, leading: 1, space: 3, shorthand: 2, dim: 2 },
  'screens/Import.tsx': { type: 16, leading: 5, space: 7, shorthand: 4, dim: 5 },
  'screens/Lesson.tsx': { type: 5, leading: 7, space: 5, dim: 3 },
  'screens/Links.tsx': { type: 6, space: 4, shorthand: 1 },
  'screens/Maps.tsx': { dim: 6 },
  'screens/Me.tsx': { type: 2, leading: 1, shorthand: 1 },
  'screens/Meals.tsx': { type: 5, leading: 1, space: 2, shorthand: 1, dim: 2 },
  'screens/Meet.tsx': { dim: 1 },
  'screens/Mine.tsx': { type: 5, leading: 4, space: 10, shorthand: 14, dim: 2 },
  'screens/Onboarding.tsx': { type: 5, leading: 1, space: 7, shorthand: 4, dim: 1 },
  'screens/People.tsx': { type: 9, leading: 3, space: 9, shorthand: 11, dim: 2 },
  'screens/Privacy.tsx': { type: 9, leading: 9, shorthand: 8, dim: 7 },
  'screens/Profile.tsx': { type: 6, leading: 2, space: 3, dim: 1 },
  'screens/Proof.tsx': { type: 1, leading: 1, space: 1, shorthand: 2 },
  'screens/Registrar.tsx': { type: 9, leading: 1, space: 4, shorthand: 2, dim: 2 },
  'screens/Runway.tsx': { type: 6, leading: 3, space: 5, shorthand: 3, dim: 1 },
  'screens/Slides.tsx': { type: 6, leading: 4, space: 2, dim: 2 },
  'screens/Solve.tsx': { type: 2, leading: 3, space: 1, shorthand: 1 },
  'screens/Sources.tsx': { type: 4, leading: 1, shorthand: 2 },
  'screens/Springboard.tsx': { type: 6, leading: 2, space: 8, shorthand: 6 },
  'screens/Study.tsx': { type: 5, leading: 3, space: 6, shorthand: 6, dim: 6 },
  'screens/Today.tsx': { type: 11, leading: 9, space: 18, shorthand: 20, dim: 8 },
  'screens/Tonight.tsx': { type: 4, leading: 2, space: 5, shorthand: 5, dim: 1 },
  'screens/Update.tsx': { type: 5, leading: 1, space: 2, shorthand: 5, dim: 4 },
  'screens/Work.tsx': { type: 12, leading: 2, space: 5, dim: 2 },
  'screens/Yes.tsx': { type: 8, space: 6, shorthand: 3, dim: 3 },
  'screens/calendar/Move.tsx': { dim: 1 },
  'screens/changes/AgainstCalendar.tsx': { type: 12, leading: 4, space: 4, shorthand: 2 },
  'screens/changes/FromText.tsx': { type: 3, leading: 2, space: 5, shorthand: 2 },
  'screens/report/Day.tsx': { type: 2, leading: 1, space: 1, shorthand: 2 },
  'screens/report/Term.tsx': { type: 3, leading: 2, shorthand: 3, dim: 2 },
  'screens/report/Week.tsx': { type: 2, leading: 2, space: 2, shorthand: 2 },
  'screens/settings/About.tsx': { space: 1, shorthand: 1 },
  'screens/settings/Alerts.tsx': { type: 6, space: 5, shorthand: 3 },
  'screens/settings/Assistant.tsx': { type: 3, shorthand: 2, dim: 1 },
  'screens/settings/Courses.tsx': { type: 3, shorthand: 4 },
  'screens/settings/Index.tsx': { type: 2, shorthand: 1 },
  'screens/settings/Look.tsx': { type: 5, space: 5, shorthand: 6 },
  'screens/settings/Nav.tsx': { type: 2, shorthand: 3 },
  'screens/settings/Page.tsx': { type: 3, leading: 1, shorthand: 3 },
};
