-- The guard from `20260921155500` found one the same afternoon it landed.
--
-- `20260921160100_lti_identity.sql` created `public.lti_link_ticket` with
--
--     provisioned_user_id uuid not null references auth.users on delete cascade
--
-- and no index on that column. `supabase/indexes.check.sql` went red on it
-- within hours of being merged, which is the argument for the guard rather
-- than a second one-off pass: the September indexing pass fixed five, this
-- branch's predecessor fixed five more fourteen days later, and a sixth
-- arrived the same day.
--
-- ## This one has its own caller, in its own migration
--
-- The general cost of an unindexed foreign key is on the parent: deleting a
-- row in `auth.users` has to prove no child references it, and without an
-- index that proof is a sequential scan of the child.
--
-- Here the parent delete is not hypothetical and not rare. The same file, at
-- the end of `lti_claim_link`, does
--
--     delete from auth.users u where u.id = got.provisioned_user_id;
--
-- which is the ordinary path when a student links a Brightspace launch to an
-- account they already had: the throwaway provisioned user is removed. So the
-- scan is on the linking path itself, once per link, growing with every ticket
-- the table has ever held.
--
-- The column alone, for the reason the earlier migration gives: nothing on
-- this table leads with it, and a composite would duplicate an index the read
-- side already has.
create index if not exists lti_link_ticket_provisioned_user
  on public.lti_link_ticket (provisioned_user_id);
