-- Emits INSERT statements for private.dq_rule: one `tenant_mismatch` rule per single-column foreign key
-- between two tenant-scoped tables (the FK does not carry tenant_id, so the database cannot stop a row
-- in one tenant referencing a parent in another).
--   psql -At -f appendix/gen_cross_tenant_rules.sql > sql/generated_dq_cross_tenant_rules.sql
-- Run against the migrated schema. Re-run when a migration adds or changes a foreign key.
select '-- GENERATED by appendix/gen_cross_tenant_rules.sql from the migrated catalog. Do not edit by hand.';
select '-- One detective rule per single-column FK between tenant-scoped tables that does not include tenant_id.';
select '-- Preferred fix is a composite foreign key (id, tenant_id); this rule is the control until it lands.';
select 'insert into private.dq_rule(rule_id,table_schema,table_name,kind,params,severity,steward) values';
select string_agg(format('(%L,%L,%L,''tenant_mismatch'',%L::jsonb,''block'',%L)',
         'tenant.' || cn.nspname || '.' || c.relname || '.' || ca.attname,
         cn.nspname, c.relname,
         jsonb_build_object('column', ca.attname, 'parent', pn.nspname || '.' || p.relname, 'parent_column', pa.attname, 'parent_tenant_column', 'tenant_id')::text,
         'Data steward, domain owner'), E',\n' order by cn.nspname, c.relname, ca.attname)
from pg_constraint k
join pg_class c on c.oid = k.conrelid  join pg_namespace cn on cn.oid = c.relnamespace
join pg_class p on p.oid = k.confrelid join pg_namespace pn on pn.oid = p.relnamespace
join pg_attribute ca on ca.attrelid = k.conrelid  and ca.attnum = k.conkey[1]
join pg_attribute pa on pa.attrelid = k.confrelid and pa.attnum = k.confkey[1]
where k.contype = 'f' and cardinality(k.conkey) = 1
  and cn.nspname in ('public','private') and pn.nspname in ('public','private')
  and k.confrelid <> 'public.schools'::regclass and k.confrelid <> 'auth.users'::regclass
  and exists (select 1 from pg_attribute a where a.attrelid = k.conrelid  and a.attname = 'tenant_id' and not a.attisdropped)
  and exists (select 1 from pg_attribute a where a.attrelid = k.confrelid and a.attname = 'tenant_id' and not a.attisdropped);
select 'on conflict do nothing;';
